//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBI.Resources.Pages.BecomeAPartner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerBI.Resources.Pages.BecomeAPartner.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy enterprise ready solutions that are scalable, extensible, and secure for your customers. Deploy pre-built analytical models and dashboards in minutes using &lt;a href=&quot;{0}&quot;&gt;Solutions Templates&lt;/a&gt;, so you can focus on the services that matter most to your organization..
        /// </summary>
        public static string AccelerateAcquisition_Content_1 {
            get {
                return ResourceManager.GetString("AccelerateAcquisition_Content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerate customer acquisition through solution templates.
        /// </summary>
        public static string AccelerateAcquisition_Title {
            get {
                return ResourceManager.GetString("AccelerateAcquisition_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string BiSolutions_Cta {
            get {
                return ResourceManager.GetString("BiSolutions_Cta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World-class BI solutions, customized for your business.
        /// </summary>
        public static string BiSolutions_Title {
            get {
                return ResourceManager.GetString("BiSolutions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlueGranite.
        /// </summary>
        public static string BlueGranite_CompanyName {
            get {
                return ResourceManager.GetString("BlueGranite_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “Power BI is now a critical part of our SI business. Over the past 18 months we’ve seen Power BI move from ‘what is it’ to ‘must have it’ with our clients, with many clients deciding Power BI is a new corporate standard. The Power BI partner program from Microsoft has helped us quickly tap into the interest and excitement from clients around this ever expanding analytics platform.”.
        /// </summary>
        public static string BlueGranite_Content {
            get {
                return ResourceManager.GetString("BlueGranite_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matt Mace.
        /// </summary>
        public static string BlueGranite_Name {
            get {
                return ResourceManager.GetString("BlueGranite_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Margin.
        /// </summary>
        public static string BlueMargin_CompanyName {
            get {
                return ResourceManager.GetString("BlueMargin_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “Our first DIAD event was filled with the most prominent companies in our region, many of whom are now in our sales pipeline.”.
        /// </summary>
        public static string BlueMargin_Content {
            get {
                return ResourceManager.GetString("BlueMargin_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sara Sanders.
        /// </summary>
        public static string BlueMargin_Name {
            get {
                return ResourceManager.GetString("BlueMargin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNet.
        /// </summary>
        public static string GNet_CompanyName {
            get {
                return ResourceManager.GetString("GNet_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “It’s unprecedented as to what Power BI Product and Engineering teams have achieved. Their outreach and community engagement with Lead Generation has enabled 1000s of users to get the most out of the best BI and Data visualization product in the market. This is the power of Microsoft’s ecosystem!”.
        /// </summary>
        public static string GNet_Content {
            get {
                return ResourceManager.GetString("GNet_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neelesh Raheja.
        /// </summary>
        public static string GNet_Name {
            get {
                return ResourceManager.GetString("GNet_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a part of the Power BI Red Carpet Program for elite industry leaders, and enjoy the benefits of technical training, webinars, direct access to Microsoft Engineering, and more..
        /// </summary>
        public static string Hero_Copy {
            get {
                return ResourceManager.GetString("Hero_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a world class Power BI Partner.
        /// </summary>
        public static string Hero_Heading {
            get {
                return ResourceManager.GetString("Hero_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showcase members have access to dedicated lead generation programs that will drive real customers who are ready to buy business intelligence solutions right to your organization. You can see it in the testimonials below – this will have a positive impact on your business..
        /// </summary>
        public static string LeverageOffers_Content {
            get {
                return ResourceManager.GetString("LeverageOffers_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leverage offers to drive demand generation.
        /// </summary>
        public static string LeverageOffers_Title {
            get {
                return ResourceManager.GetString("LeverageOffers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string META_DESCRIPTION {
            get {
                return ResourceManager.GetString("META_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string META_KEYWORDS {
            get {
                return ResourceManager.GetString("META_KEYWORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a Partner | Microsoft Power BI.
        /// </summary>
        public static string META_PAGETITLE {
            get {
                return ResourceManager.GetString("META_PAGETITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neal Analytics.
        /// </summary>
        public static string NealAnalytics_CompanyName {
            get {
                return ResourceManager.GetString("NealAnalytics_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “I was able to easily and quickly act upon the lead provided to me through the BYOD program. It’s the best Microsoft lead generation program I’ve engaged with in the 5 years I’ve been working with Microsoft.”.
        /// </summary>
        public static string NealAnalytics_Content {
            get {
                return ResourceManager.GetString("NealAnalytics_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to David Brown.
        /// </summary>
        public static string NealAnalytics_Name {
            get {
                return ResourceManager.GetString("NealAnalytics_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share and promote your fully functional Power BI solutions on the &lt;a href=&quot;{0}&quot;&gt;Microsoft Partner Showcase&lt;/a&gt;, with each displayed on a its own page as part of the Power BI website. Get your work in front of thousands of targeted potential customers, and build your brand..
        /// </summary>
        public static string ShowcaseSolutions_Content_1 {
            get {
                return ResourceManager.GetString("ShowcaseSolutions_Content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showcase your solutions on PowerBI.com.
        /// </summary>
        public static string ShowcaseSolutions_Title {
            get {
                return ResourceManager.GetString("ShowcaseSolutions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See what our partners are saying.
        /// </summary>
        public static string WhatPartnersAreSaying_Title {
            get {
                return ResourceManager.GetString("WhatPartnersAreSaying_Title", resourceCulture);
            }
        }
    }
}
