//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBI.Resources.Pages.Datajournalism {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerBI.Resources.Pages.Datajournalism.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have the goal of creating compelling data stories that are deeply engaging, capture the audience’s attention, and help others understand the information better? Power BI provides access to powerful analytics tools to help construct interesting data stories while making it easy for journalists to build and share highly interactive data visualizations..
        /// </summary>
        public static string DataVisualization_Content {
            get {
                return ResourceManager.GetString("DataVisualization_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use data visualization to enhance your stories.
        /// </summary>
        public static string DataVisualization_Heading {
            get {
                return ResourceManager.GetString("DataVisualization_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI can help you get the story to the audience. Share your story in just a few clicks with Microsoft Power BI publish to web to embed your data visualization in your blog or website. Reach unlimited views on any device. Edit, update, refresh easily and control what content you publish..
        /// </summary>
        public static string Distribute_Content {
            get {
                return ResourceManager.GetString("Distribute_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribute interactive visualizations with Power BI.
        /// </summary>
        public static string Distribute_Heading {
            get {
                return ResourceManager.GetString("Distribute_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;With Microsoft Power BI, data journalism goes beyond data exploration and allows reporters, bloggers, broadcasters, and analysts to spend their time telling stories. The data visualization tool helps emphasize messages and engage audiences through immersive and data rich stories.&lt;/p&gt;
        ///&lt;p&gt;Power BI recently teamed up with renowned visualization expert Alberto Cairo to share the methodology behind graphics and how they can support data storytelling by developing five &lt;strong&gt;Data Visualization and Storytell [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Hero_Content {
            get {
                return ResourceManager.GetString("Hero_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit the courses.
        /// </summary>
        public static string Hero_Cta {
            get {
                return ResourceManager.GetString("Hero_Cta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data visualization and storytelling.
        /// </summary>
        public static string Hero_Heading {
            get {
                return ResourceManager.GetString("Hero_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KING 5 News chose Microsoft Power BI because of the unique ability to integrate data visualizations on air, desktops and mobile devices. Microsoft also showed it is committed to providing data journalists with the technology to give viewers and readers more insights into data stories..
        /// </summary>
        public static string King5_Content {
            get {
                return ResourceManager.GetString("King5_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See what data journalists are doing with Power BI.
        /// </summary>
        public static string King5_Heading {
            get {
                return ResourceManager.GetString("King5_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string META_DESCRIPTION {
            get {
                return ResourceManager.GetString("META_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data journalism, data visualization, data storytelling, data journalism tools, Tableau, Tableau Public, Google Data Studio, Amazon QuickSight, Qlik, QlikView, publish to web.
        /// </summary>
        public static string META_KEYWORDS {
            get {
                return ResourceManager.GetString("META_KEYWORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Journalism | Microsoft Power BI.
        /// </summary>
        public static string META_PAGETITLE {
            get {
                return ResourceManager.GetString("META_PAGETITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View now.
        /// </summary>
        public static string Modal_Cta {
            get {
                return ResourceManager.GetString("Modal_Cta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email to view tutorials.
        /// </summary>
        public static string Modal_Heading {
            get {
                return ResourceManager.GetString("Modal_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best stories are often interactive, visually pleasing, and include rich data. Power BI publish to web makes it easy for media to weave interactive data visualizations into stories without requiring any code to be written..
        /// </summary>
        public static string PublishToWeb_Content {
            get {
                return ResourceManager.GetString("PublishToWeb_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View more.
        /// </summary>
        public static string PublishToWeb_Cta {
            get {
                return ResourceManager.GetString("PublishToWeb_Cta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about Power BI publish to web for storytelling.
        /// </summary>
        public static string PublishToWeb_Heading {
            get {
                return ResourceManager.GetString("PublishToWeb_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more.
        /// </summary>
        public static string SeeMore {
            get {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take advantage of Power BI.
        /// </summary>
        public static string TakeAdvantage {
            get {
                return ResourceManager.GetString("TakeAdvantage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use it free.
        /// </summary>
        public static string UseItFree_Cta {
            get {
                return ResourceManager.GetString("UseItFree_Cta", resourceCulture);
            }
        }
    }
}
