//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBI.Resources.Shared.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Form {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Form() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerBI.Resources.Shared.Forms.Form", typeof(Form).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string Company_Placeholder {
            get {
                return ResourceManager.GetString("Company_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a country to continue..
        /// </summary>
        public static string Country_RequiredMessage {
            get {
                return ResourceManager.GetString("Country_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country/region.
        /// </summary>
        public static string CountryRegion {
            get {
                return ResourceManager.GetString("CountryRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download eBook.
        /// </summary>
        public static string DownloadEbook {
            get {
                return ResourceManager.GetString("DownloadEbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered a personal email address: Please enter your work email address so we can securely store your company&apos;s data..
        /// </summary>
        public static string Email_ConsumerMessage {
            get {
                return ResourceManager.GetString("Email_ConsumerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users with .gov and .mil email addresses can use Power BI as part of the Microsoft Government Community Cloud. Please contact your Microsoft sales representative for more details. If you don’t have an existing Microsoft sales representative, please &lt;a href=&quot;https://info.microsoft.com/CO-PowerBI-ContactMe-Register.html&quot;&gt;contact us&lt;/a&gt;..
        /// </summary>
        public static string Email_DisallowedTldMessage {
            get {
                return ResourceManager.GetString("Email_DisallowedTldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address to continue..
        /// </summary>
        public static string Email_ErrorMessage {
            get {
                return ResourceManager.GetString("Email_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your work email address.
        /// </summary>
        public static string Email_Placeholder {
            get {
                return ResourceManager.GetString("Email_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address.
        /// </summary>
        public static string Email_Placeholder_2 {
            get {
                return ResourceManager.GetString("Email_Placeholder_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Email_Placeholder_3 {
            get {
                return ResourceManager.GetString("Email_Placeholder_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address required..
        /// </summary>
        public static string Email_RequiredMessage {
            get {
                return ResourceManager.GetString("Email_RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName_Placeholder {
            get {
                return ResourceManager.GetString("FirstName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Role.
        /// </summary>
        public static string Jobrole {
            get {
                return ResourceManager.GetString("Jobrole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName_Placeholder {
            get {
                return ResourceManager.GetString("LastName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid phone number to continue..
        /// </summary>
        public static string Phone_ErrorMessage {
            get {
                return ResourceManager.GetString("Phone_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number.
        /// </summary>
        public static string Phone_Placeholder {
            get {
                return ResourceManager.GetString("Phone_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work phone.
        /// </summary>
        public static string Phone_Placeholder2 {
            get {
                return ResourceManager.GetString("Phone_Placeholder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        public static string RequiredMessage {
            get {
                return ResourceManager.GetString("RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start download.
        /// </summary>
        public static string StartDownload {
            get {
                return ResourceManager.GetString("StartDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking Use it free, you agree to the &lt;a href=&quot;{0}&quot;&gt;Power BI Terms of Service&lt;/a&gt;.
        /// </summary>
        public static string Terms_GetStarted {
            get {
                return ResourceManager.GetString("Terms_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft may use your contact information to provide updates and special offers about Business Intelligence and other Microsoft products and services. You can unsubscribe at any time. To learn more you can read the &lt;a href=&quot;{0}&quot;&gt;privacy statement&lt;/a&gt;..
        /// </summary>
        public static string Terms_MsUseInfo {
            get {
                return ResourceManager.GetString("Terms_MsUseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking Track progress, you are giving your consent to Microsoft to provide you updates about Power BI learning resources via email. You can unsubscribe at any time..
        /// </summary>
        public static string Terms_TrackProgress {
            get {
                return ResourceManager.GetString("Terms_TrackProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking Use it free, you agree to the &lt;a href=&quot;{0}&quot;&gt;Power BI Terms of Service&lt;/a&gt;.
        /// </summary>
        public static string Terms_UseItFree {
            get {
                return ResourceManager.GetString("Terms_UseItFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track progress.
        /// </summary>
        public static string TrackProgress {
            get {
                return ResourceManager.GetString("TrackProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use it free.
        /// </summary>
        public static string UseItFree {
            get {
                return ResourceManager.GetString("UseItFree", resourceCulture);
            }
        }
    }
}
