//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBI.Resources.Shared.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SupportProTicket {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SupportProTicket() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerBI.Resources.Shared.Forms.SupportProTicket", typeof(SupportProTicket).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a valid category..
        /// </summary>
        public static string Category_ErrorMessage {
            get {
                return ResourceManager.GetString("Category_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category_Label {
            get {
                return ResourceManager.GetString("Category_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid country..
        /// </summary>
        public static string Country_ErrorMessage {
            get {
                return ResourceManager.GetString("Country_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country_Label {
            get {
                return ResourceManager.GetString("Country_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please agree to the disclaimer..
        /// </summary>
        public static string Disclaimer_ErrorMessage {
            get {
                return ResourceManager.GetString("Disclaimer_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept the &lt;a href=&apos;{0}&apos; target=&quot;_blank&quot; style=&quot;color: #967100;&quot;&gt;Agreement for Microsoft Services&lt;/a&gt;.
        /// </summary>
        public static string Disclaimer_Text {
            get {
                return ResourceManager.GetString("Disclaimer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email_Label {
            get {
                return ResourceManager.GetString("Email_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a valid first name..
        /// </summary>
        public static string FirstName_ErrorMessage {
            get {
                return ResourceManager.GetString("FirstName_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName_Label {
            get {
                return ResourceManager.GetString("FirstName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support is provided during business hours in the United States and currently only supported in English. Expect to hear from us within one business day..
        /// </summary>
        public static string Form_Content {
            get {
                return ResourceManager.GetString("Form_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error submitting request. Try again shortly..
        /// </summary>
        public static string Form_Error {
            get {
                return ResourceManager.GetString("Form_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        public static string Issue_Heading {
            get {
                return ResourceManager.GetString("Issue_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a valid last name..
        /// </summary>
        public static string LastName_ErrorMessage {
            get {
                return ResourceManager.GetString("LastName_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName_Label {
            get {
                return ResourceManager.GetString("LastName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your information.
        /// </summary>
        public static string PersonalInformation_Heading {
            get {
                return ResourceManager.GetString("PersonalInformation_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid phone number to continue..
        /// </summary>
        public static string Phone_ErrorMessage {
            get {
                return ResourceManager.GetString("Phone_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string Phone_Label {
            get {
                return ResourceManager.GetString("Phone_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a valid problem type..
        /// </summary>
        public static string ProblemType_ErrorMessage {
            get {
                return ResourceManager.GetString("ProblemType_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem type.
        /// </summary>
        public static string ProblemType_Label {
            get {
                return ResourceManager.GetString("ProblemType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Questions_Label {
            get {
                return ResourceManager.GetString("Questions_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a valid subject..
        /// </summary>
        public static string Subject_ErrorMessage {
            get {
                return ResourceManager.GetString("Subject_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject_Label {
            get {
                return ResourceManager.GetString("Subject_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a valid timezone..
        /// </summary>
        public static string TimeZone_ErrorMessage {
            get {
                return ResourceManager.GetString("TimeZone_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        public static string TimeZone_Label {
            get {
                return ResourceManager.GetString("TimeZone_Label", resourceCulture);
            }
        }
    }
}
