//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBI.Resources.Shared.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SupportQuestions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SupportQuestions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerBI.Resources.Shared.Forms.SupportQuestions", typeof(SupportQuestions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you experiencing stale data on your dashboards or reports?.
        /// </summary>
        public static string DataRefresh_Question1 {
            get {
                return ResourceManager.GetString("DataRefresh_Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string DataRefresh_Question1_Answer1 {
            get {
                return ResourceManager.GetString("DataRefresh_Question1_Answer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string DataRefresh_Question1_Answer2 {
            get {
                return ResourceManager.GetString("DataRefresh_Question1_Answer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the report or dashboard URL?.
        /// </summary>
        public static string DataRefresh_Question2 {
            get {
                return ResourceManager.GetString("DataRefresh_Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of data source?.
        /// </summary>
        public static string DataRefresh_Question3 {
            get {
                return ResourceManager.GetString("DataRefresh_Question3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI Desktop file.
        /// </summary>
        public static string DataRefresh_Question3_Answer1 {
            get {
                return ResourceManager.GetString("DataRefresh_Question3_Answer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Content Pack.
        /// </summary>
        public static string DataRefresh_Question3_Answer2 {
            get {
                return ResourceManager.GetString("DataRefresh_Question3_Answer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizational Content Pack.
        /// </summary>
        public static string DataRefresh_Question3_Answer3 {
            get {
                return ResourceManager.GetString("DataRefresh_Question3_Answer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis Services database.
        /// </summary>
        public static string DataRefresh_Question3_Answer4 {
            get {
                return ResourceManager.GetString("DataRefresh_Question3_Answer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure SQL Database.
        /// </summary>
        public static string DataRefresh_Question3_Answer5 {
            get {
                return ResourceManager.GetString("DataRefresh_Question3_Answer5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure SQL Data Warehouse.
        /// </summary>
        public static string DataRefresh_Question3_Answer6 {
            get {
                return ResourceManager.GetString("DataRefresh_Question3_Answer6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel File.
        /// </summary>
        public static string DataRefresh_Question3_Answer7 {
            get {
                return ResourceManager.GetString("DataRefresh_Question3_Answer7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other, please specify.
        /// </summary>
        public static string DataRefresh_Question3_Answer8 {
            get {
                return ResourceManager.GetString("DataRefresh_Question3_Answer8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If using a Power BI Desktop file, are you using Live Connect?.
        /// </summary>
        public static string DataRefresh_Question4 {
            get {
                return ResourceManager.GetString("DataRefresh_Question4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string DataRefresh_Question4_Answer1 {
            get {
                return ResourceManager.GetString("DataRefresh_Question4_Answer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string DataRefresh_Question4_Answer2 {
            get {
                return ResourceManager.GetString("DataRefresh_Question4_Answer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string DataRefresh_Question4_Answer3 {
            get {
                return ResourceManager.GetString("DataRefresh_Question4_Answer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When did the problem happen?.
        /// </summary>
        public static string DataRefresh_Question5 {
            get {
                return ResourceManager.GetString("DataRefresh_Question5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an error is thrown, please provide the full technical details, if applicable..
        /// </summary>
        public static string DataRefresh_Question6 {
            get {
                return ResourceManager.GetString("DataRefresh_Question6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What were the steps that led to the problem?.
        /// </summary>
        public static string DataRefresh_Question7 {
            get {
                return ResourceManager.GetString("DataRefresh_Question7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the issue random or permanent?.
        /// </summary>
        public static string DataRefresh_Question8 {
            get {
                return ResourceManager.GetString("DataRefresh_Question8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string DataRefresh_Question8_Answer1 {
            get {
                return ResourceManager.GetString("DataRefresh_Question8_Answer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent.
        /// </summary>
        public static string DataRefresh_Question8_Answer2 {
            get {
                return ResourceManager.GetString("DataRefresh_Question8_Answer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the source data is stored on premise, is it accessed through Personal Gateway or Data Gateway?.
        /// </summary>
        public static string DataRefresh_Question9 {
            get {
                return ResourceManager.GetString("DataRefresh_Question9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Gateway.
        /// </summary>
        public static string DataRefresh_Question9_Answer1 {
            get {
                return ResourceManager.GetString("DataRefresh_Question9_Answer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Gateway.
        /// </summary>
        public static string DataRefresh_Question9_Answer2 {
            get {
                return ResourceManager.GetString("DataRefresh_Question9_Answer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the issue and/or error and what symptoms are you seeing?.
        /// </summary>
        public static string Default_Question1 {
            get {
                return ResourceManager.GetString("Default_Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an error is thrown, please provide the full technical details, if applicable..
        /// </summary>
        public static string Default_Question2 {
            get {
                return ResourceManager.GetString("Default_Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can the problem be reproduced on demand or is this intermittent? If so, how?.
        /// </summary>
        public static string Default_Question3 {
            get {
                return ResourceManager.GetString("Default_Question3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This question is required.
        /// </summary>
        public static string Question_Required_Error {
            get {
                return ResourceManager.GetString("Question_Required_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading questions. Try again shortly..
        /// </summary>
        public static string Questions_Error {
            get {
                return ResourceManager.GetString("Questions_Error", resourceCulture);
            }
        }
    }
}
