//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBI.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Departments {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Departments() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerBI.Resources.Shared.Departments", typeof(Departments).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;Analyze campaigns in real-time&lt;/li&gt;
        ///&lt;li&gt;Identify changes in customer trends and sentiment&lt;/li&gt;
        ///&lt;li&gt;Compare actual revenue, costs, and ROI for segments, campaigns, channels, and more&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string CampaignAnalytics_Description {
            get {
                return ResourceManager.GetString("CampaignAnalytics_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn marketing data into actionable insight with interactive dashboards that make results accessible..
        /// </summary>
        public static string CampaignAnalytics_Tagline {
            get {
                return ResourceManager.GetString("CampaignAnalytics_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign Analytics.
        /// </summary>
        public static string CampaignAnalytics_Title {
            get {
                return ResourceManager.GetString("CampaignAnalytics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;Detect unexpected cost increases earlier with real-time updates&lt;/li&gt;
        ///&lt;li&gt;React quickly to changes and enable corrective action&lt;/li&gt;
        ///&lt;li&gt;Share reports out to the right teams in just a few clicks&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string CapexManagement_Description {
            get {
                return ResourceManager.GetString("CapexManagement_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free up time for strategic analysis – no more hunting for data..
        /// </summary>
        public static string CapexManagement_Tagline {
            get {
                return ResourceManager.GetString("CapexManagement_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capex Management.
        /// </summary>
        public static string CapexManagement_Title {
            get {
                return ResourceManager.GetString("CapexManagement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;Improve efficiency by analyzing metrics like past total claims, production output, or shipment times&lt;/li&gt;
        ///&lt;li&gt;See your data on a dashboard with drag-and-drop capabilities and stunning visuals&lt;/li&gt;
        ///&lt;li&gt;Maintain one version of the truth across departments and tell a clearer story&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string ClaimsAnalysis_Description {
            get {
                return ResourceManager.GetString("ClaimsAnalysis_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to React faster with mobile alerts for shipping gaps, stock shortages, and other time-sensitive needs..
        /// </summary>
        public static string ClaimsAnalysis_Tagline {
            get {
                return ResourceManager.GetString("ClaimsAnalysis_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims Analysis.
        /// </summary>
        public static string ClaimsAnalysis_Title {
            get {
                return ResourceManager.GetString("ClaimsAnalysis_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;Monitor the progress and growth of individuals against goals and role-based metrics&lt;/li&gt;
        ///&lt;li&gt;Investigate in real-time by clicking down into underlying data&lt;/li&gt;
        ///&lt;li&gt;Ask questions in natural language using Power BI’s intuitive Q&amp;amp;A format&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string ComplianceTraining_Description {
            get {
                return ResourceManager.GetString("ComplianceTraining_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make informed decisions with interactive dashboards that make detailed data accessible..
        /// </summary>
        public static string ComplianceTraining_Tagline {
            get {
                return ResourceManager.GetString("ComplianceTraining_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compliance Training.
        /// </summary>
        public static string ComplianceTraining_Title {
            get {
                return ResourceManager.GetString("ComplianceTraining_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;Leverage out-of-the-box dashboards and reports to quickly understand campaign outcomes&lt;/li&gt;
        ///&lt;li&gt;Compare results across campaigns, customer segments, and geographies&lt;/li&gt;
        ///&lt;li&gt;Discover how to better tailor your marketing approach for specific audiences&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string EmailAnalytics_Description {
            get {
                return ResourceManager.GetString("EmailAnalytics_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell the right story with real-time information that communicates important outcomes such as ROI..
        /// </summary>
        public static string EmailAnalytics_Tagline {
            get {
                return ResourceManager.GetString("EmailAnalytics_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Analytics.
        /// </summary>
        public static string EmailAnalytics_Title {
            get {
                return ResourceManager.GetString("EmailAnalytics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;Detect expense outliers and anomalies early with intuitive visualizations&lt;/li&gt;
        ///&lt;li&gt;Analyze trends and patterns to proactively search for indications of fraud and abuse&lt;/li&gt;
        ///&lt;li&gt;Ensure that your data is always fresh with automatic updates&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string ExpenseManagement_Description {
            get {
                return ResourceManager.GetString("ExpenseManagement_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a single-pane view of your financials with all of your data sources in a single model..
        /// </summary>
        public static string ExpenseManagement_Tagline {
            get {
                return ResourceManager.GetString("ExpenseManagement_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Management.
        /// </summary>
        public static string ExpenseManagement_Title {
            get {
                return ResourceManager.GetString("ExpenseManagement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you getting the answers you need about financial performance? Power BI makes it easy by collecting the data from every source, external and on-premises, and giving you drag-and-drop visualization tools to quickly analyze and explore your insights..
        /// </summary>
        public static string Finance_Description {
            get {
                return ResourceManager.GetString("Finance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert bottom lines into top strategies.
        /// </summary>
        public static string Finance_DetailTagline {
            get {
                return ResourceManager.GetString("Finance_DetailTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the answers you need from your numbers.
        /// </summary>
        public static string Finance_IndexTagline {
            get {
                return ResourceManager.GetString("Finance_IndexTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance.
        /// </summary>
        public static string Finance_Title {
            get {
                return ResourceManager.GetString("Finance_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;See all of your data in a single view, from summary statements to account-level details&lt;/li&gt;
        ///&lt;li&gt;Click to drill down into specific regions or segments&lt;/li&gt;
        ///&lt;li&gt;Make decisions faster with real-time updates&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string FinancialPerformance_Description {
            get {
                return ResourceManager.GetString("FinancialPerformance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the full picture across different data sources in seconds..
        /// </summary>
        public static string FinancialPerformance_Tagline {
            get {
                return ResourceManager.GetString("FinancialPerformance_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Performance.
        /// </summary>
        public static string FinancialPerformance_Title {
            get {
                return ResourceManager.GetString("FinancialPerformance_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;Gain insight into the latest trends in employee retention and turnover&lt;/li&gt;
        ///&lt;li&gt;Stay current by scheduling automatic data refresh&lt;/li&gt;
        ///&lt;li&gt;Enable mobile alerts to inform you of changes to your recruiting pipeline&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string HeadcountSummary_Description {
            get {
                return ResourceManager.GetString("HeadcountSummary_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan more effectively by viewing current and forecasted needs in one place..
        /// </summary>
        public static string HeadcountSummary_Tagline {
            get {
                return ResourceManager.GetString("HeadcountSummary_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headcount Summary.
        /// </summary>
        public static string HeadcountSummary_Title {
            get {
                return ResourceManager.GetString("HeadcountSummary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;Streamline ticket resolution by optimizing Help Desk resources based on trend data&lt;/li&gt;
        ///&lt;li&gt;Visually compare key metrics in real-time, including Help Desk traffic and top issues&lt;/li&gt;
        ///&lt;li&gt;Build better relationships with your customers by reducing help ticket satisfaction&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string HelpDesk_Description {
            get {
                return ResourceManager.GetString("HelpDesk_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify risks sooner by tracking key metrics in real-time..
        /// </summary>
        public static string HelpDesk_Tagline {
            get {
                return ResourceManager.GetString("HelpDesk_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Desk.
        /// </summary>
        public static string HelpDesk_Title {
            get {
                return ResourceManager.GetString("HelpDesk_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to stay up-to-date on the progress of your initiatives? Power BI has tools to easily collect and monitor all of your important data. Better protect your colleagues and your organization with insightful dashboards to track compliance, headcount, and more..
        /// </summary>
        public static string HumanResources_Description {
            get {
                return ResourceManager.GetString("HumanResources_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn your data into new opportunities.
        /// </summary>
        public static string HumanResources_DetailTagline {
            get {
                return ResourceManager.GetString("HumanResources_DetailTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get data-driven policymaking for your organization.
        /// </summary>
        public static string HumanResources_IndexTagline {
            get {
                return ResourceManager.GetString("HumanResources_IndexTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Resources.
        /// </summary>
        public static string HumanResources_Title {
            get {
                return ResourceManager.GetString("HumanResources_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to improve productivity in a quick and affordable way? With Power BI, you can create dashboards in seconds that monitor and analyze everything from Active Directory to Zendesk, and it integrates seamlessly with SSAS for when you need enterprise-scale BI solutions..
        /// </summary>
        public static string IT_Description {
            get {
                return ResourceManager.GetString("IT_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Business Intelligence more accessible.
        /// </summary>
        public static string IT_DetailTagline {
            get {
                return ResourceManager.GetString("IT_DetailTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor all of your systems from one dashboard.
        /// </summary>
        public static string IT_IndexTagline {
            get {
                return ResourceManager.GetString("IT_IndexTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT.
        /// </summary>
        public static string IT_Title {
            get {
                return ResourceManager.GetString("IT_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;Connect Power BI easily to other tools&lt;/li&gt;
        ///&lt;li&gt;Integrate Power BI with your existing solutions for an end-to-end approach to data analytics&lt;/li&gt;
        ///&lt;li&gt;Work equally well with Microsoft products like Azure Active Directory and non-Microsoft products like SAP&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string ITSpend_Description {
            get {
                return ResourceManager.GetString("ITSpend_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See everything in one place including network systems, services, applications, and security data..
        /// </summary>
        public static string ITSpend_Tagline {
            get {
                return ResourceManager.GetString("ITSpend_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT Spend.
        /// </summary>
        public static string ITSpend_Title {
            get {
                return ResourceManager.GetString("ITSpend_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you overwhelmed by data from all the different tools you use? Make it simple: with Power BI, you can easily monitor and analyze your marketing campaigns and efficiently allocate your resources to the right channels, all in one place..
        /// </summary>
        public static string Marketing_Description {
            get {
                return ResourceManager.GetString("Marketing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build profitable customer relationships.
        /// </summary>
        public static string Marketing_DetailTagline {
            get {
                return ResourceManager.GetString("Marketing_DetailTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor all your campaigns from one dashboard.
        /// </summary>
        public static string Marketing_IndexTagline {
            get {
                return ResourceManager.GetString("Marketing_IndexTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        public static string Marketing_Title {
            get {
                return ResourceManager.GetString("Marketing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;Publish and present Market Share leveraging interactive visualizations&lt;/li&gt;
        ///&lt;li&gt;Take corrective action faster with enhanced visibility to all aspects of the campaign&lt;/li&gt;
        ///&lt;li&gt;Share your findings anywhere, including mobile&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string MarketShare_Description {
            get {
                return ResourceManager.GetString("MarketShare_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find actionable insights and publish them instantly to interactive dashboards accessible from all devices..
        /// </summary>
        public static string MarketShare_Tagline {
            get {
                return ResourceManager.GetString("MarketShare_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Share.
        /// </summary>
        public static string MarketShare_Title {
            get {
                return ResourceManager.GetString("MarketShare_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is your organization truly data-driven? With Power BI you can quickly monitor and engage with your data from all sources, including Excel workbooks, on-premises databases, and cloud services. Find new insights for your production, store performance, claims analysis, and more..
        /// </summary>
        public static string Operations_Description {
            get {
                return ResourceManager.GetString("Operations_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay a step ahead of demand.
        /// </summary>
        public static string Operations_DetailTagline {
            get {
                return ResourceManager.GetString("Operations_DetailTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engage with your data and find new efficiencies.
        /// </summary>
        public static string Operations_IndexTagline {
            get {
                return ResourceManager.GetString("Operations_IndexTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string Operations_Title {
            get {
                return ResourceManager.GetString("Operations_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;Track your sales pipeline in real-time&lt;/li&gt;
        ///&lt;li&gt;Accurately inform sales forecasts and plans&lt;/li&gt;
        ///&lt;li&gt;Easily connect and manipulate data in one location for more comprehensive analysis&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string PipelineReports_Description {
            get {
                return ResourceManager.GetString("PipelineReports_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make more informed decisions by quickly accessing detailed sales data..
        /// </summary>
        public static string PipelineReports_Tagline {
            get {
                return ResourceManager.GetString("PipelineReports_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline Reports.
        /// </summary>
        public static string PipelineReports_Title {
            get {
                return ResourceManager.GetString("PipelineReports_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;Lead stand-up meetings on the factory floor with live dashboards&lt;/li&gt;
        ///&lt;li&gt;Optimize manufacturing performance&lt;/li&gt;
        ///&lt;li&gt;Easily identify areas for process improvement&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string Production_Description {
            get {
                return ResourceManager.GetString("Production_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improve insight by combining data from production to distribution..
        /// </summary>
        public static string Production_Tagline {
            get {
                return ResourceManager.GetString("Production_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string Production_Title {
            get {
                return ResourceManager.GetString("Production_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;Gain insight into sales progress against forecasts&lt;/li&gt;
        ///&lt;li&gt;Easily analyze the performance of specific geographies or individual account owners&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string QuotaManagement_Description {
            get {
                return ResourceManager.GetString("QuotaManagement_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make data-driven decisions about the future based on past and present information..
        /// </summary>
        public static string QuotaManagement_Tagline {
            get {
                return ResourceManager.GetString("QuotaManagement_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota Management.
        /// </summary>
        public static string QuotaManagement_Title {
            get {
                return ResourceManager.GetString("QuotaManagement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;React quickly to the latest revenue data with on-demand reports&lt;/li&gt;
        ///&lt;li&gt;Mash up data to identify variances&lt;/li&gt;
        ///&lt;li&gt;Forecast with enough time to course correct when necessary&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string RevenueProfitability_Description {
            get {
                return ResourceManager.GetString("RevenueProfitability_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliver answers fast with executive-level financial dashboards..
        /// </summary>
        public static string RevenueProfitability_Tagline {
            get {
                return ResourceManager.GetString("RevenueProfitability_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue &amp; Profitability.
        /// </summary>
        public static string RevenueProfitability_Title {
            get {
                return ResourceManager.GetString("RevenueProfitability_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to forecast sales better, hit that record sales target, and increase profitability per sale? Power BI brings your company&apos;s sales pipeline under a magnifying glass in seconds with dashboards that include your Microsoft Dynamics CRM or Salesforce.com data..
        /// </summary>
        public static string Sales_Description {
            get {
                return ResourceManager.GetString("Sales_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert bottom lines into top strategies.
        /// </summary>
        public static string Sales_DetailTagline {
            get {
                return ResourceManager.GetString("Sales_DetailTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crush you quotas and forecast better for the future.
        /// </summary>
        public static string Sales_IndexTagline {
            get {
                return ResourceManager.GetString("Sales_IndexTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string Sales_Title {
            get {
                return ResourceManager.GetString("Sales_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;Leverage live data and real-time dashboards to review current sales performance&lt;/li&gt;
        ///&lt;li&gt;Easily identify underperforming areas of your business&lt;/li&gt;
        ///&lt;li&gt;Determine the variance between actual revenue and sales targets by segment&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string SalesPerformance_Description {
            get {
                return ResourceManager.GetString("SalesPerformance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a single, holistic view of your sales performance across segments..
        /// </summary>
        public static string SalesPerformance_Tagline {
            get {
                return ResourceManager.GetString("SalesPerformance_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Performance.
        /// </summary>
        public static string SalesPerformance_Title {
            get {
                return ResourceManager.GetString("SalesPerformance_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;Enhance network security with early visibility of compliance risks&lt;/li&gt;
        ///&lt;li&gt;Track adherence to security, software, and other standards in real time&lt;/li&gt;
        ///&lt;li&gt;Pool security data, like network access logs, and display it visually on a single dashboard&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string SecurityCompliance_Description {
            get {
                return ResourceManager.GetString("SecurityCompliance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give your users data independence through easer report development that combines multiple sources into a single model..
        /// </summary>
        public static string SecurityCompliance_Tagline {
            get {
                return ResourceManager.GetString("SecurityCompliance_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security &amp; Compliance.
        /// </summary>
        public static string SecurityCompliance_Title {
            get {
                return ResourceManager.GetString("SecurityCompliance_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;Stay on top of your allocation across geographies&lt;/li&gt;
        ///&lt;li&gt;Closely manage inventory counts with live metrics that tell the whole story&lt;/li&gt;
        ///&lt;li&gt;Easily spot trends to better analyze which product to prioritize&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string StorePerformance_Description {
            get {
                return ResourceManager.GetString("StorePerformance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep teams on the same page by sharing the latest operational data in a few clicks..
        /// </summary>
        public static string StorePerformance_Tagline {
            get {
                return ResourceManager.GetString("StorePerformance_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Performance.
        /// </summary>
        public static string StorePerformance_Title {
            get {
                return ResourceManager.GetString("StorePerformance_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string SubNavTitle {
            get {
                return ResourceManager.GetString("SubNavTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;Track sales trends to optimize strategies and inform long-term business plans&lt;/li&gt;
        ///&lt;li&gt;Share insights with sales teams&lt;/li&gt;
        ///&lt;li&gt;Dynamically adjust your tactics and update in real-time across all devices&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string Trends_Description {
            get {
                return ResourceManager.GetString("Trends_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep your team informed by quickly sharing interactive visuals with others..
        /// </summary>
        public static string Trends_Tagline {
            get {
                return ResourceManager.GetString("Trends_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trends.
        /// </summary>
        public static string Trends_Title {
            get {
                return ResourceManager.GetString("Trends_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;Track customer sentiment in real-time&lt;/li&gt;
        ///&lt;li&gt;Tailor your web and social campaigns based on emerging trends&lt;/li&gt;
        ///&lt;li&gt;Monitor customer reaction to social media tactics&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string WebSocialAnalytics_Description {
            get {
                return ResourceManager.GetString("WebSocialAnalytics_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the big picture by viewing web, email, and social analytics in one place..
        /// </summary>
        public static string WebSocialAnalytics_Tagline {
            get {
                return ResourceManager.GetString("WebSocialAnalytics_Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web &amp; Social Analytics.
        /// </summary>
        public static string WebSocialAnalytics_Title {
            get {
                return ResourceManager.GetString("WebSocialAnalytics_Title", resourceCulture);
            }
        }
    }
}
