//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBI.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Industries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Industries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerBI.Resources.Shared.Industries", typeof(Industries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Operations Engineers at major airlines, responsible for a fleet of aircraft, must constantly weigh the cost and disruption of ad hoc maintenance against the risk and even higher cost of technical failures. &lt;/p&gt;
        ///&lt;p&gt;The report in this solution provides an overview of the fleet’s status as well as a summary of predictions for near term changes to the fleet’s technical health.  The predictions are based on multiple machine learning models and use the aircrafts&apos; Quick Access Recorder (similar to the Black Bo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Airline_DetailsTagline {
            get {
                return ResourceManager.GetString("Airline_DetailsTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving maintenance planning at a massive scale.
        /// </summary>
        public static string Airline_DetailTitle {
            get {
                return ResourceManager.GetString("Airline_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This solution is based on a real world predictive maintenance system for a major airline. The data comes from a variety of sources including IoT data streams from aircraft engines, flight plans, weather information and logs. The solution leverages Azure HDInsight for feature engineering, Azure Machine Learning to detect operational anomalies and Azure SQL DW to enable high performance querying on the resulting petabytes of data. This report also shows the use of custom visualizations designed for the airlin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Airline_IndexTagline {
            get {
                return ResourceManager.GetString("Airline_IndexTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airline.
        /// </summary>
        public static string Airline_Title {
            get {
                return ResourceManager.GetString("Airline_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The U.S. Personal Consumption Expenditure Dashboard is used by Microsoft’s Treasury organization to track spending trends (in trillions of USD) on over 200 individual goods and services (anything from automobiles to museum memberships) purchased in the United States. The dataset is published on a monthly basis by the Bureau of Economic Analysis and is organized into an eight level hierarchy which Power BI can instantly drill into to see changes at the most granular level. This dashboard allows Microsoft to  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CapitalMarkets_DetailsTagline {
            get {
                return ResourceManager.GetString("CapitalMarkets_DetailsTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The U.S. Personal Consumption Expenditure dashboard tracks consumer spending in the US across a wide range of goods and services to track the US business cycle as well as gauge spending trends and economic sentiment.
        /// </summary>
        public static string CapitalMarkets_IndexTagline {
            get {
                return ResourceManager.GetString("CapitalMarkets_IndexTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital Markets.
        /// </summary>
        public static string CapitalMarkets_Title {
            get {
                return ResourceManager.GetString("CapitalMarkets_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Consumer Packaged Products is competitive industry. All brands and categories fight every day for customer attention and preference. Growing your market share is hard and CPG analytics is the only way to excel. &lt;/p&gt;
        ///&lt;p&gt;Monitor all key metrics in one place with Power BI: stock levels, profitability, supply chain, channels and pricing. Avoid out of stock situations with real time reports and alerts. &lt;/p&gt;
        ///&lt;p&gt;Manage your global footprint with high level dashboards and drill down where data show you deeper  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CPG_DetailsTagline {
            get {
                return ResourceManager.GetString("CPG_DetailsTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grow market share through deeper data analysis and trend understanding.
        /// </summary>
        public static string CPG_DetailTitle {
            get {
                return ResourceManager.GetString("CPG_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer products sit at the center of the following disciplines: operations, marketing, sales and finance to name a few. Analyze constantly changing data to maximize sales, profits and customer loyalty..
        /// </summary>
        public static string CPG_IndexTagline {
            get {
                return ResourceManager.GetString("CPG_IndexTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Packaged Goods (CPG).
        /// </summary>
        public static string CPG_Title {
            get {
                return ResourceManager.GetString("CPG_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Storing energy is not cost-effective, so utilities and power generators need to forecast future power consumption so that they can efficiently balance the supply with the demand. During peak hours, short supply can result in power outages. Conversely, too much supply can result in waste of resources. Advanced demand forecasting techniques detail hourly demand and peak hours for a particular day, allowing an energy provider to optimize the power generation process. This report focuses on demand forecastin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Energy_DetailsTagline {
            get {
                return ResourceManager.GetString("Energy_DetailsTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        public static string Energy_DetailTitle {
            get {
                return ResourceManager.GetString("Energy_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report focuses on demand forecasting within the energy sector. The views provide region level energy usage status and forecast of future usage for optimizing the operations..
        /// </summary>
        public static string Energy_IndexTagline {
            get {
                return ResourceManager.GetString("Energy_IndexTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        public static string Energy_Title {
            get {
                return ResourceManager.GetString("Energy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Managing risk is the most important goal for insurance companies. But the amount of data and variables that go into insurance analytics is huge and needs tools and approaches that help insurance professionals to quickly identify trends and act on them. &lt;/p&gt;
        ///&lt;p&gt;Power BI helps insurance analysts to visualize claims, premiums, fraud, sales and customer satisfaction data with ease and in one place. Spot claims and payment trends faster. &lt;/p&gt;
        ///&lt;p&gt;Identify patterns that could lead to fraud detection and set u [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Insurance_DetailsTagline {
            get {
                return ResourceManager.GetString("Insurance_DetailsTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor risk, manage sales and claims, and detect fraud with visual data driven analysis.
        /// </summary>
        public static string Insurance_DetailTitle {
            get {
                return ResourceManager.GetString("Insurance_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is pouring in from insurance companies operations: policy sales, claims, fraud, coverage complexity and premiums all provide companies with a rich set of trends and insights that are waiting to tapped..
        /// </summary>
        public static string Insurance_IndexTagline {
            get {
                return ResourceManager.GetString("Insurance_IndexTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance.
        /// </summary>
        public static string Insurance_Title {
            get {
                return ResourceManager.GetString("Insurance_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Track key performance indicators in real time: machine utilization, process efficiency, costs, inventory levels, losses and cycle times. &lt;/p&gt;
        ///&lt;p&gt;Manufacturers need to collaborate, monitor and communicate on available live data to achieve operational excellence. Power BI helps your team monitor real time data from multiple sources into one dashboard and drill down to identify issues when necessary. Get real time alerts with Power BI mobile apps and make your operations more efficient to achieve greater a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Manufacturing_DetailsTagline {
            get {
                return ResourceManager.GetString("Manufacturing_DetailsTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real time visibility into your supply chain for more efficient and faster decisions.
        /// </summary>
        public static string Manufacturing_DetailTitle {
            get {
                return ResourceManager.GetString("Manufacturing_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The manufacturing process needs to be a well-oiled machine to succeed and the best way of achieving that goal is to have visibility on every process while seeing the big picture..
        /// </summary>
        public static string Manufacturing_IndexTagline {
            get {
                return ResourceManager.GetString("Manufacturing_IndexTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturing.
        /// </summary>
        public static string Manufacturing_Title {
            get {
                return ResourceManager.GetString("Manufacturing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;It doesn’t matter if your firm specializes in consulting, legal services, real estate services or healthcare. Your business moves around people. You need to monitor performance with the right KPIs to maximize results and increase efficiency. You need to share that data with your people to act quickly and improve results. &lt;/p&gt;
        ///&lt;p&gt;Power BI allows you to monitor the right KPIs, personalize them, visualize for better understanding and share them, all on the same platform. Calculate live metrics such as annu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProfessionalServices_DetailsTagline {
            get {
                return ResourceManager.GetString("ProfessionalServices_DetailsTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus on your people with deeper data insights.
        /// </summary>
        public static string ProfessionalServices_DetailTitle {
            get {
                return ResourceManager.GetString("ProfessionalServices_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional services firms have one thing in common: their most important asset is their people. Support your professionals with the right data and technology to maximize value delivered to your clients..
        /// </summary>
        public static string ProfessionalServices_IndexTagline {
            get {
                return ResourceManager.GetString("ProfessionalServices_IndexTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Services.
        /// </summary>
        public static string ProfessionalServices_Title {
            get {
                return ResourceManager.GetString("ProfessionalServices_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Education&lt;/h3&gt;
        ///&lt;p&gt;As the statistics show, enrolment in Primary Education is growing apace as progress is made in particular in the developing world, partly on foot of the Millennium Development Goals which prioritized primary school enrolment. However, almost 1 in 10 children globally are still out of school and a disproportionate number of these (60%) are girls. Enrollment in Higher Education has also grown but remains at a low level globally, with huge disparities between nations in the developed and [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PublicSector_DetailsTagline {
            get {
                return ResourceManager.GetString("PublicSector_DetailsTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Sector data is available via various sources online. Most of these data sources are free as well. This provides with an amazing opportunity to correlate how the public policies are affecting changes from Climate to Education to Health and more..
        /// </summary>
        public static string PublicSector_IndexTagline {
            get {
                return ResourceManager.GetString("PublicSector_IndexTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Sector.
        /// </summary>
        public static string PublicSector_Title {
            get {
                return ResourceManager.GetString("PublicSector_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;The amount of data available for retailers is overwhelming: transactions, supply chain, buying behaviors, trends, multi-channel sales and global coverage are just a few of the data sources companies can use to maximize their profits. &lt;/p&gt;
        ///&lt;p&gt;Making sense of all these inputs requires scalability, ease of use, accessibility and live connectivity. Power BI helps bring all these data sources in one place and keeps the data current allowing you to make the right decisions at the right time. Share your retail [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Retail_DetailsTagline {
            get {
                return ResourceManager.GetString("Retail_DetailsTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deeper understanding of customers, pricing, POS, inventory and channels.
        /// </summary>
        public static string Retail_DetailTitle {
            get {
                return ResourceManager.GetString("Retail_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping is not what it used to be. Today shoppers are empowered with devices, options and more information at their fingertips. Get visibility into the insights that will make your business successful..
        /// </summary>
        public static string Retail_IndexTagline {
            get {
                return ResourceManager.GetString("Retail_IndexTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail.
        /// </summary>
        public static string Retail_Title {
            get {
                return ResourceManager.GetString("Retail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Businesses need an effective strategy for managing customer churn. Customer churn includes customers stopping the use of a service, switching to a competitor service, switching to a lower-tier experience in the service or reducing engagement with the service.&lt;/p&gt;
        ///&lt;p&gt;In this use case, we look at how a mobile phone carrier company can leverage Azure to proactively identify customers more likely to churn in the near term in order to improve the service and create custom outreach campaigns that help retain  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Telecommunications_DetailsTagline {
            get {
                return ResourceManager.GetString("Telecommunications_DetailsTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone Carrier.
        /// </summary>
        public static string Telecommunications_DetailTitle {
            get {
                return ResourceManager.GetString("Telecommunications_DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn how a telecommunication company, operating a mobile business, can leverage Cortana Intelligence Suite and Power BI to empower business stakeholders to analyze factors contributing to customer churn..
        /// </summary>
        public static string Telecommunications_IndexTagline {
            get {
                return ResourceManager.GetString("Telecommunications_IndexTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telecommunications.
        /// </summary>
        public static string Telecommunications_Title {
            get {
                return ResourceManager.GetString("Telecommunications_Title", resourceCulture);
            }
        }
    }
}
