//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBI.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IntegrationsNew {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IntegrationsNew() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerBI.Resources.Shared.IntegrationsNew", typeof(IntegrationsNew).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Power BI you can develop compelling visual reports that bring together your Acumatica ERP data (financials, distribution, manufacturing, accounting, CRM) and your other data sources in one place. Obtain a 360° view of your business in minutes with easy to use, drag and drop, pre-built dashboards and reports..
        /// </summary>
        public static string acumatica_Content {
            get {
                return ResourceManager.GetString("acumatica_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhance your Acumatica data by integrating it with other applications in minutes..
        /// </summary>
        public static string acumatica_Heading {
            get {
                return ResourceManager.GetString("acumatica_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acumatica.
        /// </summary>
        public static string acumatica_Name {
            get {
                return ResourceManager.GetString("acumatica_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify broader correlations from your Acumatica data easily. With the flexibility of Power BI you can quickly gain insights into your data to uncover the hidden relationships or patterns leading to new opportunities to improve productivity and business operations..
        /// </summary>
        public static string acumatica_SubContent1 {
            get {
                return ResourceManager.GetString("acumatica_SubContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare your Acumatica CRM data side by side, against applications like Marketo marketing automation, and Google Analytics website data. Connect to dozens of other leading business applications in a few easy steps, leading to new insights and enhanced data clarity..
        /// </summary>
        public static string acumatica_SubContent2 {
            get {
                return ResourceManager.GetString("acumatica_SubContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and store visually impactful dashboards and reports safely. Share your reports with colleagues - anytime, anywhere. With the Microsoft industry-leading cloud computing platform, your data is always secure..
        /// </summary>
        public static string acumatica_SubContent3 {
            get {
                return ResourceManager.GetString("acumatica_SubContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Power BI you can develop compelling visual reports that bring together your Adobe Analytics digital marketing data and your other data sources in one place. Obtain a 360° view of your business in minutes with easy to use, drag and drop, pre-built dashboards and reports..
        /// </summary>
        public static string adobe_analytics_Content {
            get {
                return ResourceManager.GetString("adobe_analytics_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhance your Adobe Analytics data by integrating it with other applications in minutes..
        /// </summary>
        public static string adobe_analytics_Heading {
            get {
                return ResourceManager.GetString("adobe_analytics_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adobe Analytics.
        /// </summary>
        public static string adobe_analytics_Name {
            get {
                return ResourceManager.GetString("adobe_analytics_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify broader correlations from your Adobe analytics digital marketing data easily. With the flexibility of Power BI you can quickly gain insights into your data to uncover the hidden relationships or patterns leading to new opportunities, innovative marketing, and attracting new customers..
        /// </summary>
        public static string adobe_analytics_SubContent1 {
            get {
                return ResourceManager.GetString("adobe_analytics_SubContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare your Adobe Analytics digital marketing data , side by side, against application like Salesforce CRM, Marketo marketing automation, and Google Analytics website data. Connect to dozens of other leading business applications in a few easy steps, leading to new insights and enhanced data clarity..
        /// </summary>
        public static string adobe_analytics_SubContent2 {
            get {
                return ResourceManager.GetString("adobe_analytics_SubContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and store visually impactful dashboards and reports safely. Share your reports with colleagues - anytime, anywhere. With the Microsoft industry-leading cloud computing platform, your data is always secure..
        /// </summary>
        public static string adobe_analytics_SubContent3 {
            get {
                return ResourceManager.GetString("adobe_analytics_SubContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickly create visual reports, analytics, and dashboards from your data, all highly interactive and easy to share..
        /// </summary>
        public static string default_Content {
            get {
                return ResourceManager.GetString("default_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get better dashboards and reports for your data.
        /// </summary>
        public static string default_Heading {
            get {
                return ResourceManager.GetString("default_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify broader correlations from your data easily. With the flexibility of Power BI you can quickly gain insights into your data to uncover the hidden relationships or patterns leading to new opportunities, innovative marketing, and attracting new customers..
        /// </summary>
        public static string default_SubContent1 {
            get {
                return ResourceManager.GetString("default_SubContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare your data, side by side, against applications like Salesforce CRM, Marketo marketing automation, and Adobe digital marketing data. Connect to dozens of other leading business applications in a few easy steps, leading to new insights and enhanced data clarity..
        /// </summary>
        public static string default_SubContent2 {
            get {
                return ResourceManager.GetString("default_SubContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and store visually impactful dashboards and reports safely. Share your reports with colleagues - anytime, anywhere. With the Microsoft industry-leading cloud computing platform, your data is always secure..
        /// </summary>
        public static string default_SubContent3 {
            get {
                return ResourceManager.GetString("default_SubContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instantly visualize and analyze.
        /// </summary>
        public static string default_SubHeading1 {
            get {
                return ResourceManager.GetString("default_SubHeading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare and contrast data         ///across all your apps.
        /// </summary>
        public static string default_SubHeading2 {
            get {
                return ResourceManager.GetString("default_SubHeading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share seamlessly.
        /// </summary>
        public static string default_SubHeading3 {
            get {
                return ResourceManager.GetString("default_SubHeading3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Integration.
        /// </summary>
        public static string default_Title {
            get {
                return ResourceManager.GetString("default_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Power BI you can develop compelling visual reports that bring together your Google Analytics website data and your other data sources in one place. Obtain a 360° view of your business in minutes with easy to use, drag and drop, pre-built dashboards and reports..
        /// </summary>
        public static string google_analytics_Content {
            get {
                return ResourceManager.GetString("google_analytics_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhance your Google Analytics data by integrating it with other applications in minutes.
        /// </summary>
        public static string google_analytics_Heading {
            get {
                return ResourceManager.GetString("google_analytics_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Analytics.
        /// </summary>
        public static string google_analytics_Name {
            get {
                return ResourceManager.GetString("google_analytics_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify broader correlations from your Google Analytics website data easily. With the flexibility of Power BI you can quickly gain insights into your data to uncover the hidden relationships or patterns leading to new opportunities, innovative marketing, and attracting new customers..
        /// </summary>
        public static string google_analytics_SubContent1 {
            get {
                return ResourceManager.GetString("google_analytics_SubContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare your Google Analytics website data, side by side, against applications like Salesforce CRM, Marketo marketing automation, and Adobe digital marketing data. Connect to dozens of other leading business applications in a few easy steps, leading to new insights and enhanced data clarity..
        /// </summary>
        public static string google_analytics_SubContent2 {
            get {
                return ResourceManager.GetString("google_analytics_SubContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and store visually impactful dashboards and reports safely. Share your reports with colleagues - anytime, anywhere. With the Microsoft industry-leading cloud computing platform, your data is always secure..
        /// </summary>
        public static string google_analytics_SubContent3 {
            get {
                return ResourceManager.GetString("google_analytics_SubContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Power BI you can develop compelling visual reports that bring together your Salesforce CRM data and your other data sources in one place. Obtain a 360° view of your business in minutes with easy to use, drag and drop, pre-built dashboards and reports..
        /// </summary>
        public static string salesforce_Content {
            get {
                return ResourceManager.GetString("salesforce_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhance your Salesforce Analytics data by integrating it with other applications in minutes..
        /// </summary>
        public static string salesforce_Heading {
            get {
                return ResourceManager.GetString("salesforce_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesforce.
        /// </summary>
        public static string salesforce_Name {
            get {
                return ResourceManager.GetString("salesforce_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify broader correlations from your Salesforce CRM data  easily. With the flexibility of Power BI you can quickly gain insights into your data to uncover the hidden relationships or patterns leading to new opportunities, innovative marketing, and attracting new customers..
        /// </summary>
        public static string salesforce_SubContent1 {
            get {
                return ResourceManager.GetString("salesforce_SubContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare your Salesforce CRM data , side by side, against applications like Adobe Analytics digital marketing, Marketo marketing automation, and Google Analytics website data. Connect to dozens of other leading business applications in a few easy steps, leading to new insights and enhanced data clarity..
        /// </summary>
        public static string salesforce_SubContent2 {
            get {
                return ResourceManager.GetString("salesforce_SubContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and store visually impactful dashboards and reports safely. Share your reports with colleagues - anytime, anywhere. With the Microsoft industry-leading cloud computing platform, your data is always secure..
        /// </summary>
        public static string salesforce_SubContent3 {
            get {
                return ResourceManager.GetString("salesforce_SubContent3", resourceCulture);
            }
        }
    }
}
