//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBI.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PublishToWebStories {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PublishToWebStories() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerBI.Resources.Shared.PublishToWebStories", typeof(PublishToWebStories).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The capabilities of Power BI have been harnessed to showcase data collected by India’s community health worker- the ASHA, and highlights key touch points through the continuum of care from pregnancy into postpartum. The dashboard can be showcased, both to an international or local audience for program management and visibility..
        /// </summary>
        public static string CatholicReliefServices_Details {
            get {
                return ResourceManager.GetString("CatholicReliefServices_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catholic Relief Services.
        /// </summary>
        public static string CatholicReliefServices_Title {
            get {
                return ResourceManager.GetString("CatholicReliefServices_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI publish to web is helping the Civic Innovation Project advance its mission of supporting cities across the world work better with data and make transparency a daily part of governance. It’s helping the Civic Innovation Project teach leaders how civic technology can integrate a data-driven decision-making process into the daily work that impacts citizens, and engages them in learning about their community..
        /// </summary>
        public static string CivicInnovationProject_Details {
            get {
                return ResourceManager.GetString("CivicInnovationProject_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civic Innovation Project.
        /// </summary>
        public static string CivicInnovationProject_Title {
            get {
                return ResourceManager.GetString("CivicInnovationProject_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Power BI publish to web feature allows EGPAF to use all the powerful tools of Power BI to make a compelling data dashboard that is readily available and accessible to a variety of audiences. EGPAF now has a more exciting and meaningful way to use data to tell their story and highlight efforts to end AIDS in children worldwide..
        /// </summary>
        public static string ElizabethGlaser_Details {
            get {
                return ResourceManager.GetString("ElizabethGlaser_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elizabeth Glaser Pediatric AIDS Foundation.
        /// </summary>
        public static string ElizabethGlaser_Title {
            get {
                return ResourceManager.GetString("ElizabethGlaser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the latest Power BI publish to web technology, JJ Foods Services can publish relevant data on websites or blogs to give easy access with interactive reports to external partners. This simple but very effective method has opened new doors for data sharing..
        /// </summary>
        public static string JJFoodServices_Details {
            get {
                return ResourceManager.GetString("JJFoodServices_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JJ Foods Services.
        /// </summary>
        public static string JJFoodServices_Title {
            get {
                return ResourceManager.GetString("JJFoodServices_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Working with Microsoft and Power BI gave KING 5 a huge advantage over other local news media on election night. Real-time results were available online and on our mobile app at the same time our reporters interacted with them on the air. That’s not just good journalism, it’s great customer service. Power BI lets KING 5 engage our audience in ways we’ve never been able to before.&quot; - Cheryl Carson, KING 5 news director..
        /// </summary>
        public static string King5_Details {
            get {
                return ResourceManager.GetString("King5_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King 5.
        /// </summary>
        public static string King5_Title {
            get {
                return ResourceManager.GetString("King5_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pact works on the ground in more than 30 countries, focused on making lives measurably better around the globe.  Power BI provides Pact an interactive visualization tool that has helped the organization to more simply and powerfully showcase the impact of its work. Power BI allows Pact&apos;s staff, donors and partners to access information quickly, see results across countries and sectors, and track trends over time..
        /// </summary>
        public static string Pact_Details {
            get {
                return ResourceManager.GetString("Pact_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pact.
        /// </summary>
        public static string Pact_Title {
            get {
                return ResourceManager.GetString("Pact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building capacities of people, their institutions, government functionaries and the sector agencies is a key strategy of WaterAid India. Microsoft Power BI has helped WaterAid monitor data from different geographies and themes. Power BI provides interactive visuals and user friendly tools to transform and analyze key data points, helping management navigate easily across multiple layers to assess progress and gaps. With Power BI publish to web capability, WaterAid is able to easily communicate important ana [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WaterAid_Details {
            get {
                return ResourceManager.GetString("WaterAid_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaterAid.
        /// </summary>
        public static string WaterAid_Title {
            get {
                return ResourceManager.GetString("WaterAid_Title", resourceCulture);
            }
        }
    }
}
