//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBI.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShowcaseIndustries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShowcaseIndustries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerBI.Resources.Shared.ShowcaseIndustries", typeof(ShowcaseIndustries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agriculture.
        /// </summary>
        public static string Agriculture {
            get {
                return ResourceManager.GetString("Agriculture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architecture + Engineering.
        /// </summary>
        public static string ArchitectureAndEngineering {
            get {
                return ResourceManager.GetString("ArchitectureAndEngineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution.
        /// </summary>
        public static string Distribution {
            get {
                return ResourceManager.GetString("Distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial services.
        /// </summary>
        public static string FinancialServices {
            get {
                return ResourceManager.GetString("FinancialServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government.
        /// </summary>
        public static string Government {
            get {
                return ResourceManager.GetString("Government", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health care + life sciences.
        /// </summary>
        public static string HealthCareAndLifeSciences {
            get {
                return ResourceManager.GetString("HealthCareAndLifeSciences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospitality and Travel.
        /// </summary>
        public static string HospitalityAndTravel {
            get {
                return ResourceManager.GetString("HospitalityAndTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturing.
        /// </summary>
        public static string Manufacturing {
            get {
                return ResourceManager.GetString("Manufacturing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media and Entertainment.
        /// </summary>
        public static string MediaAndEntertainment {
            get {
                return ResourceManager.GetString("MediaAndEntertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National and Public Security.
        /// </summary>
        public static string NationalAndPublicSecurity {
            get {
                return ResourceManager.GetString("NationalAndPublicSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nonprofit.
        /// </summary>
        public static string Nonprofit {
            get {
                return ResourceManager.GetString("Nonprofit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power &amp; Utilities.
        /// </summary>
        public static string PowerAndUtilities {
            get {
                return ResourceManager.GetString("PowerAndUtilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Services.
        /// </summary>
        public static string ProfessionalServices {
            get {
                return ResourceManager.GetString("ProfessionalServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Estate.
        /// </summary>
        public static string RealEstate {
            get {
                return ResourceManager.GetString("RealEstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail and Consumer Goods.
        /// </summary>
        public static string RetailAndConsumerGoods {
            get {
                return ResourceManager.GetString("RetailAndConsumerGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telecommunications.
        /// </summary>
        public static string Telecommunications {
            get {
                return ResourceManager.GetString("Telecommunications", resourceCulture);
            }
        }
    }
}
