//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBI.Resources.Pages.Datajournalism.Courses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ChoosingGraphics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChoosingGraphics() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerBI.Resources.Pages.Datajournalism.Courses.ChoosingGraphics", typeof(ChoosingGraphics).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Additionally, you’ll be walked through a series of Microsoft Power BI demos. These include the following: &lt;ul&gt;&lt;li&gt;Learn how to use a bullet chart custom visualization to merge data together as an efficient way to show insights.&lt;/li&gt;
        ///&lt;li&gt;Look at how to plot geographical data from an urban development dataset pulled from The World Bank to visualize a circle map, field map and create a map from R script. &lt;/li&gt;&lt;li&gt;Understand how to appropriately set axes by watching demos using climate change data from The  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About_Content {
            get {
                return ResourceManager.GetString("About_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 id=&quot;creating-chart&quot;&gt;Creating a Bullet Chart in Power BI&lt;/h2&gt;
        ///
        ///&lt;p&gt;To follow the examples shown in this course, you will need the following
        ///prerequisites:&lt;/p&gt;
        ///
        ///&lt;ol&gt;
        ///&lt;li&gt;&lt;p&gt;A computer running Windows 7 or above&lt;/p&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;p&gt;Download and install &lt;a href=&quot;{0}&quot;&gt;Power BI
        ///Desktop&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;p&gt;Register for a Power BI account
        ///(&lt;a href=&quot;{1}&quot;&gt;{2}&lt;/a&gt;)&lt;/p&gt;
        ///
        ///&lt;p&gt;a.  Note you will need to register using a work email account;
        ///    personal accounts (gmail, Hotmail, outlook.com, yahoo.com) are
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Article_Content_10 {
            get {
                return ResourceManager.GetString("Article_Content_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download all the resources needed for these tutorials.
        /// </summary>
        public static string Download_Resources {
            get {
                return ResourceManager.GetString("Download_Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alberto Cairo will teach you how to appropriately choose the right graphics for your data. The human brain is more efficient at seeing patterns and trends when they are transformed into bar charts, line charts, data maps, scatter charts and other graphics. Alberto provides topics and questions to follow to help determine which graphic representation would be most appropriate for your data. You’ll be given an overview on what types of graphics enable accurate estimates and what types of visuals enable genera [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Hero_Subtitle {
            get {
                return ResourceManager.GetString("Hero_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosing Graphics.
        /// </summary>
        public static string Hero_Title {
            get {
                return ResourceManager.GetString("Hero_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this article:.
        /// </summary>
        public static string InThisArticle {
            get {
                return ResourceManager.GetString("InThisArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string META_DESCRIPTION {
            get {
                return ResourceManager.GetString("META_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string META_KEYWORDS {
            get {
                return ResourceManager.GetString("META_KEYWORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Journalism - Choosing Graphics | Microsoft Power BI.
        /// </summary>
        public static string META_PAGETITLE {
            get {
                return ResourceManager.GetString("META_PAGETITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Topic: Design Narrative.
        /// </summary>
        public static string NextTopic {
            get {
                return ResourceManager.GetString("NextTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a Bullet Chart in Power BI.
        /// </summary>
        public static string RightNav_Link1 {
            get {
                return ResourceManager.GetString("RightNav_Link1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Data Maps (Using the R Visual to Draw a Dotted Map).
        /// </summary>
        public static string RightNav_Link2 {
            get {
                return ResourceManager.GetString("RightNav_Link2", resourceCulture);
            }
        }
    }
}
