//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBI.Resources.Pages.Datajournalism.Courses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DesignNarrative {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DesignNarrative() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerBI.Resources.Pages.Datajournalism.Courses.DesignNarrative", typeof(DesignNarrative).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;You’ll also receive Microsoft Power BI demos highlighting the below: &lt;ul&gt;
        ///    &lt;li&gt;Walk step-by-step through how to makeover a poorly designed pie chart into a clean and concise looking tree map and bar chart that enables the audience to take away a key insight. &lt;/li&gt;
        ///    &lt;li&gt;Receive a demo on how to apply Alberto’s design principles to an interactive data visualization that’s worthy of being published on a blog or in an online article. &lt;/li&gt;
        ///    &lt;li&gt;Discover how to use animation, interaction and narra [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About_Content {
            get {
                return ResourceManager.GetString("About_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 id=&quot;synoptic-panel&quot;&gt;Synoptic panel&lt;/h2&gt;
        ///
        ///&lt;p&gt;To follow the examples shown in this course, you will need the following
        ///prerequisites:&lt;/p&gt;
        ///&lt;ol&gt;
        ///&lt;li&gt;&lt;p&gt;A computer running Windows 7 or above&lt;/p&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;p&gt;Download and install &lt;a href=&quot;{0}&quot;&gt;Power BI
        ///Desktop&lt;/a&gt;&lt;/p&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;p&gt;Register for a Power BI account
        ///(&lt;a href=&quot;{1}&quot;&gt;{1}&lt;/a&gt;)&lt;/p&gt;
        ///&lt;p&gt;a.  Note you will need to register using a work email account;
        ///    personal accounts (gmail, Hotmail, outlook.com, yahoo.com) are
        ///    not supported&lt;/p&gt;&lt;/li&gt;
        ///&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Article_Content_26 {
            get {
                return ResourceManager.GetString("Article_Content_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download all the resources needed for these tutorials.
        /// </summary>
        public static string Download_Resources {
            get {
                return ResourceManager.GetString("Download_Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During the last course Alberto Cairo will cover visual design including typography, color, composition, pictorial elements, how to arrange your graphics in narratives, and what you can expect to see in the future. Alberto will discuss why visual design matters and should not be an afterthought..
        /// </summary>
        public static string Hero_Subtitle {
            get {
                return ResourceManager.GetString("Hero_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design and Narrative.
        /// </summary>
        public static string Hero_Title {
            get {
                return ResourceManager.GetString("Hero_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this article:.
        /// </summary>
        public static string InThisArticle {
            get {
                return ResourceManager.GetString("InThisArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string META_DESCRIPTION {
            get {
                return ResourceManager.GetString("META_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string META_KEYWORDS {
            get {
                return ResourceManager.GetString("META_KEYWORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Journalism - Design and Narrative | Microsoft Power BI.
        /// </summary>
        public static string META_PAGETITLE {
            get {
                return ResourceManager.GetString("META_PAGETITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synoptic Panel.
        /// </summary>
        public static string RightNav_Link1 {
            get {
                return ResourceManager.GetString("RightNav_Link1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augmented Reality with Power BI.
        /// </summary>
        public static string RightNav_Link2 {
            get {
                return ResourceManager.GetString("RightNav_Link2", resourceCulture);
            }
        }
    }
}
