//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBI.Resources.Pages.Datajournalism.Courses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerBI.Resources.Pages.Datajournalism.Courses.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn how to appropriately choose the graphic forms to showcase your data.
        /// </summary>
        public static string ChoosingGraphics_Content {
            get {
                return ResourceManager.GetString("ChoosingGraphics_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosing Graphics.
        /// </summary>
        public static string ChoosingGraphics_Heading {
            get {
                return ResourceManager.GetString("ChoosingGraphics_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use visualizations to understand and explore your data to extract meaning.
        /// </summary>
        public static string DataExploration_Content {
            get {
                return ResourceManager.GetString("DataExploration_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Exploration.
        /// </summary>
        public static string DataExploration_Heading {
            get {
                return ResourceManager.GetString("DataExploration_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore design concepts to create compelling data visualizations.
        /// </summary>
        public static string DesignNarrative_Content {
            get {
                return ResourceManager.GetString("DesignNarrative_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design and Narrative.
        /// </summary>
        public static string DesignNarrative_Heading {
            get {
                return ResourceManager.GetString("DesignNarrative_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Welcome to the &lt;strong&gt;Data Visualization and Storytelling&lt;/strong&gt; section for Microsoft Power BI. We have teamed up with renowned data visualization expert &lt;a href=&quot;{0}&quot;&gt;Alberto Cairo&lt;/a&gt; to share the methodology behind visualization and how it can support data storytelling. The goal of these courses is to show that visualization is a powerful tool that can help form a narrative and present valuable insights to your audience in a compelling way.&lt;/p&gt;
        ///&lt;p&gt;        ///We have layered in Power BI demos and tutorials  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Hero_Content {
            get {
                return ResourceManager.GetString("Hero_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start learning.
        /// </summary>
        public static string Hero_Cta {
            get {
                return ResourceManager.GetString("Hero_Cta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Storytelling and Visualization.
        /// </summary>
        public static string Hero_Title {
            get {
                return ResourceManager.GetString("Hero_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leverage graphics of different kinds to understand your data and communicate it with your audience.
        /// </summary>
        public static string IntroToVisualization_Content {
            get {
                return ResourceManager.GetString("IntroToVisualization_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction to Visualization.
        /// </summary>
        public static string IntroToVisualization_Heading {
            get {
                return ResourceManager.GetString("IntroToVisualization_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string META_DESCRIPTION {
            get {
                return ResourceManager.GetString("META_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string META_KEYWORDS {
            get {
                return ResourceManager.GetString("META_KEYWORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Journalism Courses | Microsoft Power BI.
        /// </summary>
        public static string META_PAGETITLE {
            get {
                return ResourceManager.GetString("META_PAGETITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present the information you want to share effectively and truthfully.
        /// </summary>
        public static string TruthfulVisualizations_Content {
            get {
                return ResourceManager.GetString("TruthfulVisualizations_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truthful Visualizations.
        /// </summary>
        public static string TruthfulVisualizations_Heading {
            get {
                return ResourceManager.GetString("TruthfulVisualizations_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch now.
        /// </summary>
        public static string WatchNow_Cta {
            get {
                return ResourceManager.GetString("WatchNow_Cta", resourceCulture);
            }
        }
    }
}
