//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBI.Resources.Pages.PartnerShowcase {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerBI.Resources.Pages.PartnerShowcase.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to discover the right BI solution for your business data? Our certified partners have a wealth of experience across a wide number of industries and technologies. Browse the Partner Solution Showcase now to find the right solution for your organization..
        /// </summary>
        public static string Hero_Content {
            get {
                return ResourceManager.GetString("Hero_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See what our partners are doing with Power BI.
        /// </summary>
        public static string Hero_Heading {
            get {
                return ResourceManager.GetString("Hero_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string LearnMore_Cta {
            get {
                return ResourceManager.GetString("LearnMore_Cta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI tranforms your company&apos;s data into rich visuals for you to collect and organize so you can focus on what matters to you. Stay in the know, spot trends as they happen, and push your business further..
        /// </summary>
        public static string META_DESCRIPTION {
            get {
                return ResourceManager.GetString("META_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string META_KEYWORDS {
            get {
                return ResourceManager.GetString("META_KEYWORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner showcase | Microsoft Power BI.
        /// </summary>
        public static string META_PAGETITLE {
            get {
                return ResourceManager.GetString("META_PAGETITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No partners match the criteria you selected. Please try again..
        /// </summary>
        public static string NoMatch_Content {
            get {
                return ResourceManager.GetString("NoMatch_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry.
        /// </summary>
        public static string NoMatch_Heading {
            get {
                return ResourceManager.GetString("NoMatch_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Partners.
        /// </summary>
        public static string Search_Partners {
            get {
                return ResourceManager.GetString("Search_Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Countries.
        /// </summary>
        public static string Selector_Countries {
            get {
                return ResourceManager.GetString("Selector_Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Departments.
        /// </summary>
        public static string Selector_Departments {
            get {
                return ResourceManager.GetString("Selector_Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Industries.
        /// </summary>
        public static string Selector_Industries {
            get {
                return ResourceManager.GetString("Selector_Industries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World-class BI solutions, customized for your business.
        /// </summary>
        public static string Solutions_Heading {
            get {
                return ResourceManager.GetString("Solutions_Heading", resourceCulture);
            }
        }
    }
}
