//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBI.Resources.Pages.ComparePowerBITableauQlik {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerBI.Resources.Pages.ComparePowerBITableauQlik.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to multiple data sources with Power BI. Whether your data lives in a cloud service such as Marketo or Salesforce, or on-premises, Power BI enables you to connect, clean, shape, model, and visualize it with live reports and dashboards. Get started in minutes with Content Packs, pre-built dashboards, and reports for popular services..
        /// </summary>
        public static string ConnectData_Content {
            get {
                return ResourceManager.GetString("ConnectData_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View list of content services you can connect to.
        /// </summary>
        public static string ConnectData_Cta1 {
            get {
                return ResourceManager.GetString("ConnectData_Cta1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See iOS, Windows, and Android mobile apps.
        /// </summary>
        public static string ConnectData_Cta2 {
            get {
                return ResourceManager.GetString("ConnectData_Cta2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any data, any way, anywhere.
        /// </summary>
        public static string ConnectData_Heading {
            get {
                return ResourceManager.GetString("ConnectData_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No need to write code or be a stats guru to get actionable insights. Power BI Q&amp;A allows you to ask questions and get super-fast answers in the form of charts and graphs ready for pinning to your dashboards. Cortana will answer your questions using Power BI, without leaving the Cortana panel..
        /// </summary>
        public static string Content1 {
            get {
                return ResourceManager.GetString("Content1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As of March 2016, 5 million subscribers and 200,000 organizations worldwide use Power BI..
        /// </summary>
        public static string Customers_Content {
            get {
                return ResourceManager.GetString("Customers_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read customer stories.
        /// </summary>
        public static string Customers_Cta {
            get {
                return ResourceManager.GetString("Customers_Cta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI is not limited to “what’s in the box”. With Custom visuals, Power BI allows you to have any visualization you can imagine..
        /// </summary>
        public static string CustomVisuals_Content {
            get {
                return ResourceManager.GetString("CustomVisuals_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit the Custom Visuals gallery.
        /// </summary>
        public static string CustomVisuals_Cta {
            get {
                return ResourceManager.GetString("CustomVisuals_Cta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom visualizations.
        /// </summary>
        public static string CustomVisuals_Heading {
            get {
                return ResourceManager.GetString("CustomVisuals_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlike other interactive data visualization tools..
        /// </summary>
        public static string Download_Content {
            get {
                return ResourceManager.GetString("Download_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Power BI Desktop.
        /// </summary>
        public static string Download_Cta {
            get {
                return ResourceManager.GetString("Download_Cta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI Desktop is free.
        /// </summary>
        public static string Download_Heading {
            get {
                return ResourceManager.GetString("Download_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Because Power BI is cloud-based, you can add or remove users anytime. Plus, it offers 99.9 percent uptime. You get scalable, highly secure, and reliable enterprise-grade IT with optimized costs that are based on the number of users and their specific data needs. You can also reduce your IT investment in your extract-transform-load infrastructure through built-in connectivity to a variety of data sources, both in the cloud and on-premises. And since Power BI is designed as an integral part of Microsoft en [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmbedReports_Content {
            get {
                return ResourceManager.GetString("EmbedReports_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string EmbedReports_Cta {
            get {
                return ResourceManager.GetString("EmbedReports_Cta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise-ready.
        /// </summary>
        public static string EmbedReports_Heading {
            get {
                return ResourceManager.GetString("EmbedReports_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience your data in new ways.
        /// </summary>
        public static string Heading1 {
            get {
                return ResourceManager.GetString("Heading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional BI tools, such as Tableau, Qlik, etc., are solutions for analysts that provide rearview mirror intelligence on what has happened. In contrast, Power BI is business analytics service that can empower everyone—not just data specialists—with real- time insight to what is happening. With Power BI, it takes five minutes to start creating personalized dashboards to find answers to the most important questions for your business..
        /// </summary>
        public static string Hero_Content {
            get {
                return ResourceManager.GetString("Hero_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started free.
        /// </summary>
        public static string Hero_Cta {
            get {
                return ResourceManager.GetString("Hero_Cta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for a modern data visualization tool?.
        /// </summary>
        public static string Hero_Heading {
            get {
                return ResourceManager.GetString("Hero_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI tranforms your company&apos;s data into rich visuals for you to collect and organize so you can focus on what matters to you. Stay in the know, spot trends as they happen, and push your business further..
        /// </summary>
        public static string META_DESCRIPTION {
            get {
                return ResourceManager.GetString("META_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string META_KEYWORDS {
            get {
                return ResourceManager.GetString("META_KEYWORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Power BI | Microsoft Power BI.
        /// </summary>
        public static string META_PAGETITLE {
            get {
                return ResourceManager.GetString("META_PAGETITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since the beginning, Power BI has been engineered so it can be easily used with Excel, Office 365, Azure, and SQL Server. Upload Excel reports to Power BI and pin items to a Power BI dashboard or use them as a data source. Take advantage of your current investments while empowering your people to find new actionable insights with familiar tools..
        /// </summary>
        public static string MicrosoftIntegrations_Content {
            get {
                return ResourceManager.GetString("MicrosoftIntegrations_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Power BI publisher for Excel.
        /// </summary>
        public static string MicrosoftIntegrations_Cta {
            get {
                return ResourceManager.GetString("MicrosoftIntegrations_Cta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy to use with other Microsoft products and services.
        /// </summary>
        public static string MicrosoftIntegrations_Heading {
            get {
                return ResourceManager.GetString("MicrosoftIntegrations_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC Magazine awarded Power BI its Editor’s Choice award in “The Best Self-Service Business Intelligence (BI) Tools of 2016” article..
        /// </summary>
        public static string PCmag_Content {
            get {
                return ResourceManager.GetString("PCmag_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the article.
        /// </summary>
        public static string PCmag_Cta {
            get {
                return ResourceManager.GetString("PCmag_Cta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No need to write code or be a stats guru to get actionable insights. Power BI Q&amp;A allows you to ask questions and get super-fast answers in the form of charts and graphs ready for pinning to your dashboards. Through deep integration with Windows 10, Cortana makes BI as easy as search, right on your desktop..
        /// </summary>
        public static string QandA_Content {
            get {
                return ResourceManager.GetString("QandA_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience your data in new ways.
        /// </summary>
        public static string QandA_Heading {
            get {
                return ResourceManager.GetString("QandA_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto search datasets for hidden insights in seconds with Quick Insights: correlations, outliers, seasonality, change points in trends, and major factors, from specific dashboard tiles and its related data..
        /// </summary>
        public static string QuickInsights_Content {
            get {
                return ResourceManager.GetString("QuickInsights_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically search datasets for hidden insights.
        /// </summary>
        public static string QuickInsights_Heading {
            get {
                return ResourceManager.GetString("QuickInsights_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rather than using traditional BI tools like Tableau or Qlik where you’re limited to historical analysis, Power BI lets you access real-time information to identify trends early. That way, you can head off potential issues and improve performance sooner rather than later. With advanced analytics integration through R scripts and visuals, Microsoft Azure Machine Learning, and Azure Stream Analytics, use your data to predict outcomes for your business. Predictive intelligence can help you take proactive action [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Realtime_Content {
            get {
                return ResourceManager.GetString("Realtime_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot trends in real time and make better, more informed decisions.
        /// </summary>
        public static string Realtime_Heading {
            get {
                return ResourceManager.GetString("Realtime_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t just take our word for it.
        /// </summary>
        public static string Recommendations_Heading {
            get {
                return ResourceManager.GetString("Recommendations_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;With Power BI, you get nonstop innovation to help you visualize and analyze data with greater speed, efficiency, and understanding. Our vibrant user community provides continuous feedback that helps guide weekly and monthly releases of Power BI—so your analytics tools just keep getting better and better. Because Power BI is cloud-based, you get the updates automatically—no software upgrades to worry about. &lt;/p&gt;
        ///&lt;p&gt;And Power BI offers an open strategy for users to create and share custom visualizations s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Sanddance_Content {
            get {
                return ResourceManager.GetString("Sanddance_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch SandDance in action.
        /// </summary>
        public static string Sanddance_Cta1 {
            get {
                return ResourceManager.GetString("Sanddance_Cta1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the Power BI blog about SandDance.
        /// </summary>
        public static string Sanddance_Cta2 {
            get {
                return ResourceManager.GetString("Sanddance_Cta2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-driven innovation at cloud speed.
        /// </summary>
        public static string Sanddance_Heading {
            get {
                return ResourceManager.GetString("Sanddance_Heading", resourceCulture);
            }
        }
    }
}
