//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBI.Resources.Pages.Pricing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexB() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerBI.Resources.Pages.Pricing.IndexB", typeof(IndexB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The free companion authoring tool for you to create stunning reports and visualizations to share with others—with new features and updates monthly..
        /// </summary>
        public static string Desktop_Content {
            get {
                return ResourceManager.GetString("Desktop_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///&lt;li&gt;Transform and clean data&lt;/li&gt;
        ///&lt;li&gt;Drag-and-drop to create stunning reports and visualizations&lt;/li&gt;
        ///&lt;li&gt;Publish reports and dashboards to Power BI service&lt;/li&gt;
        ///&lt;li&gt;Custom visuals&lt;/li&gt;
        ///&lt;li&gt;R integration&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string Desktop_Free_Features {
            get {
                return ResourceManager.GetString("Desktop_Free_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI Desktop.
        /// </summary>
        public static string Desktop_Title {
            get {
                return ResourceManager.GetString("Desktop_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download for free.
        /// </summary>
        public static string DownloadFree {
            get {
                return ResourceManager.GetString("DownloadFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Data capacity limit details&lt;/h3&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;Global limit for tenant = 10 GB x # of Power BI Pro seats purchased&lt;/li&gt;
        ///&lt;li&gt;Limit for a single personal workspace = 10 GB&lt;/li&gt;
        ///&lt;li&gt;Limit for a single group = 10 GB&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string Flyout_Capacity {
            get {
                return ResourceManager.GetString("Flyout_Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Power BI REST API Limits&lt;/h3&gt;
        ///&lt;p&gt;This is the max data rate for the Power BI REST API. See &lt;a href=&quot;{0}&quot;&gt;Power BI REST API Limits&lt;/a&gt; for more information.&lt;/p&gt;.
        /// </summary>
        public static string Flyout_MaxDataRate {
            get {
                return ResourceManager.GetString("Flyout_MaxDataRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For authoring.
        /// </summary>
        public static string ForAuthoring {
            get {
                return ResourceManager.GetString("ForAuthoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For businesses.
        /// </summary>
        public static string ForBusinesses {
            get {
                return ResourceManager.GetString("ForBusinesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For individuals.
        /// </summary>
        public static string ForIndividuals {
            get {
                return ResourceManager.GetString("ForIndividuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to cloud sources.
        /// </summary>
        public static string Free_ConnectCloud {
            get {
                return ResourceManager.GetString("Free_ConnectCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10K rows per hour streaming data.
        /// </summary>
        public static string Free_Features_10kRows {
            get {
                return ResourceManager.GetString("Free_Features_10kRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///1GB per user data capacity.
        /// </summary>
        public static string Free_Features_1GB {
            get {
                return ResourceManager.GetString("Free_Features_1GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily scheduled data refresh.
        /// </summary>
        public static string Free_Features_DailyRefresh {
            get {
                return ResourceManager.GetString("Free_Features_DailyRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple dashboard sharing.
        /// </summary>
        public static string Free_SimpleShare {
            get {
                return ResourceManager.GetString("Free_SimpleShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI is cloud-based business analytics service that gives you and others a single view of your most critical business data—with new features and updates weekly. Get insights into your data in 5 minutes or less. Sign up and try it for free today..
        /// </summary>
        public static string Hero_Content {
            get {
                return ResourceManager.GetString("Hero_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string Hero_Heading {
            get {
                return ResourceManager.GetString("Hero_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI tranforms your company&apos;s data into rich visuals for you to collect and organize so you can focus on what matters to you. Stay in the know, spot trends as they happen, and push your business further..
        /// </summary>
        public static string META_DESCRIPTION {
            get {
                return ResourceManager.GetString("META_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string META_KEYWORDS {
            get {
                return ResourceManager.GetString("META_KEYWORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing | Microsoft Power BI.
        /// </summary>
        public static string META_PAGETITLE {
            get {
                return ResourceManager.GetString("META_PAGETITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;p&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;Prices shown per user per month but annual subscription is required.&lt;/li&gt;
        ///&lt;li&gt;Academic, Government and Non-profit pricing available.&lt;/li&gt;
        ///&lt;li&gt;Learn more about volume Licensing or find a Microsoft expert.&lt;/li&gt;
        ///&lt;li&gt;Pricing shown in US dollars for Commercial ERP through the Microsoft Online Subscription Program.&lt;/li&gt;
        ///&lt;li&gt;Tenants can have a mix of users with Power BI (free) and Power BI Pro licenses&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;/p&gt;.
        /// </summary>
        public static string Other_Info {
            get {
                return ResourceManager.GetString("Other_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI service.
        /// </summary>
        public static string PowerBIFree {
            get {
                return ResourceManager.GetString("PowerBIFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI Pro service.
        /// </summary>
        public static string PowerBIPro {
            get {
                return ResourceManager.GetString("PowerBIPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access on-premise data using gateways.
        /// </summary>
        public static string Pro_AccessData {
            get {
                return ResourceManager.GetString("Pro_AccessData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10GB per user data capacity.
        /// </summary>
        public static string Pro_Features_10GB {
            get {
                return ResourceManager.GetString("Pro_Features_10GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1M rows per hour streaming data.
        /// </summary>
        public static string Pro_Features_1MRows {
            get {
                return ResourceManager.GetString("Pro_Features_1MRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaborate with your team using Office 365 Groups.
        /// </summary>
        public static string Pro_Features_CollaborateOffice365 {
            get {
                return ResourceManager.GetString("Pro_Features_CollaborateOffice365", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to live data sources with full interactivity.
        /// </summary>
        public static string Pro_Features_ConnectLive {
            get {
                return ResourceManager.GetString("Pro_Features_ConnectLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly scheduled data refresh.
        /// </summary>
        public static string Pro_Features_HourlyRefresh {
            get {
                return ResourceManager.GetString("Pro_Features_HourlyRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage access and sharing through Active Directory.
        /// </summary>
        public static string Pro_Features_ManageAccessSharing {
            get {
                return ResourceManager.GetString("Pro_Features_ManageAccessSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared data queries through Data Catalog.
        /// </summary>
        public static string Pro_Features_SharedDataQueries {
            get {
                return ResourceManager.GetString("Pro_Features_SharedDataQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise grade sharing with content packs.
        /// </summary>
        public static string Pro_ShareContentPacks {
            get {
                return ResourceManager.GetString("Pro_ShareContentPacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&lt;span class=&quot;text-regular&quot;&gt;/ user / month&lt;/span&gt;.
        /// </summary>
        public static string Rate_PerUserPerMonth {
            get {
                return ResourceManager.GetString("Rate_PerUserPerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use it free.
        /// </summary>
        public static string UseItFree {
            get {
                return ResourceManager.GetString("UseItFree", resourceCulture);
            }
        }
    }
}
