//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBI.Resources.Shared.Lefties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class datajournalism {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal datajournalism() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerBI.Resources.Shared.Lefties.datajournalism", typeof(datajournalism).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosing Graphics.
        /// </summary>
        public static string Area_ChoosingGraphics {
            get {
                return ResourceManager.GetString("Area_ChoosingGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Exploration.
        /// </summary>
        public static string Area_DataExploration {
            get {
                return ResourceManager.GetString("Area_DataExploration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Narrative.
        /// </summary>
        public static string Area_DesignNarrative {
            get {
                return ResourceManager.GetString("Area_DesignNarrative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truthful Visualizations.
        /// </summary>
        public static string Area_TruthfulVisualizations {
            get {
                return ResourceManager.GetString("Area_TruthfulVisualizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizations.
        /// </summary>
        public static string Area_Visualizations {
            get {
                return ResourceManager.GetString("Area_Visualizations", resourceCulture);
            }
        }
    }
}
