//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBI.Resources.Shared.Lefties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class mobile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal mobile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerBI.Resources.Shared.Lefties.mobile", typeof(mobile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Mobile Apps.
        /// </summary>
        public static string Area_AllMobileApps {
            get {
                return ResourceManager.GetString("Area_AllMobileApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI app for Android phones.
        /// </summary>
        public static string Area_Android {
            get {
                return ResourceManager.GetString("Area_Android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI app for Android tablets.
        /// </summary>
        public static string Area_AndroidTablet {
            get {
                return ResourceManager.GetString("Area_AndroidTablet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        public static string Area_GetStarted {
            get {
                return ResourceManager.GetString("Area_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad app (Power BI for iOS).
        /// </summary>
        public static string Area_iPad {
            get {
                return ResourceManager.GetString("Area_iPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone app (Power BI for iOS).
        /// </summary>
        public static string Area_iPhone {
            get {
                return ResourceManager.GetString("Area_iPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI app for Windows 10 devices.
        /// </summary>
        public static string Area_Windows {
            get {
                return ResourceManager.GetString("Area_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started with the Power BI for Android app.
        /// </summary>
        public static string Link_AndroidGetStarted {
            get {
                return ResourceManager.GetString("Link_AndroidGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Reporting Services mobile reports and KPIs in the Android app.
        /// </summary>
        public static string Link_AndroidKPIs {
            get {
                return ResourceManager.GetString("Link_AndroidKPIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixing &apos;your corporate SSL certificate is untrusted&apos;.
        /// </summary>
        public static string Link_AndroidNotSignYouIn {
            get {
                return ResourceManager.GetString("Link_AndroidNotSignYouIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports in the Power BI app for Android devices.
        /// </summary>
        public static string Link_AndroidReports {
            get {
                return ResourceManager.GetString("Link_AndroidReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started with the Power BI for Android tablet app.
        /// </summary>
        public static string Link_AndroidTabGetStarted {
            get {
                return ResourceManager.GetString("Link_AndroidTabGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiles in the Android tablet app.
        /// </summary>
        public static string Link_AndroidTabTiles {
            get {
                return ResourceManager.GetString("Link_AndroidTabTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiles in the Android app.
        /// </summary>
        public static string Link_AndroidTiles {
            get {
                return ResourceManager.GetString("Link_AndroidTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI Apple Watch app.
        /// </summary>
        public static string Link_AppleWatch {
            get {
                return ResourceManager.GetString("Link_AppleWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI apps for mobile devices.
        /// </summary>
        public static string Link_Apps {
            get {
                return ResourceManager.GetString("Link_Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboards for mobile Power BI.
        /// </summary>
        public static string Link_CreateDashboard {
            get {
                return ResourceManager.GetString("Link_CreateDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite items in the Power BI mobile apps.
        /// </summary>
        public static string Link_Favorites {
            get {
                return ResourceManager.GetString("Link_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter a report by location in the Power BI mobile apps.
        /// </summary>
        public static string Link_Geofiltering {
            get {
                return ResourceManager.GetString("Link_Geofiltering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure mobile apps with Intune.
        /// </summary>
        public static string Link_Intune {
            get {
                return ResourceManager.GetString("Link_Intune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask questions about your data in the iOS mobile apps (Tutorial).
        /// </summary>
        public static string Link_iosQnA {
            get {
                return ResourceManager.GetString("Link_iosQnA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started with the iPad app.
        /// </summary>
        public static string Link_iPadGetStarted {
            get {
                return ResourceManager.GetString("Link_iPadGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work in group workspaces in the mobile apps.
        /// </summary>
        public static string Link_iPadGroups {
            get {
                return ResourceManager.GetString("Link_iPadGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports on the iPad app.
        /// </summary>
        public static string Link_iPadReports {
            get {
                return ResourceManager.GetString("Link_iPadReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interact with tiles in the iPad app.
        /// </summary>
        public static string Link_iPadTiles {
            get {
                return ResourceManager.GetString("Link_iPadTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI for iOS apps.
        /// </summary>
        public static string Link_iPhoneApps {
            get {
                return ResourceManager.GetString("Link_iPhoneApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started with the Power BI for iOS app on an iPhone.
        /// </summary>
        public static string Link_iPhoneGetStarted {
            get {
                return ResourceManager.GetString("Link_iPhoneGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known issue with &apos;communication failures&apos; in iOS mobile apps.
        /// </summary>
        public static string Link_iPhoneIssues {
            get {
                return ResourceManager.GetString("Link_iPhoneIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create picture tiles with your iPhone app.
        /// </summary>
        public static string Link_iPhonePictureTiles {
            get {
                return ResourceManager.GetString("Link_iPhonePictureTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan a Power BI QR code from your phone.
        /// </summary>
        public static string Link_iPhoneQRCode {
            get {
                return ResourceManager.GetString("Link_iPhoneQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports in the iPhone app.
        /// </summary>
        public static string Link_iPhoneReports {
            get {
                return ResourceManager.GetString("Link_iPhoneReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan a barcode from the Power BI app on your iPhone.
        /// </summary>
        public static string Link_iPhoneScanBarcode {
            get {
                return ResourceManager.GetString("Link_iPhoneScanBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set data alerts in the Power BI mobile apps.
        /// </summary>
        public static string Link_iPhoneSetAlerts {
            get {
                return ResourceManager.GetString("Link_iPhoneSetAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share a dashboard from the Power BI mobile apps.
        /// </summary>
        public static string Link_iPhoneShareDashboard {
            get {
                return ResourceManager.GetString("Link_iPhoneShareDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotate &amp; share a tile, report, or visual in the mobile apps.
        /// </summary>
        public static string Link_iPhoneShareTiles {
            get {
                return ResourceManager.GetString("Link_iPhoneShareTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interact with tiles in the mobile apps.
        /// </summary>
        public static string Link_iPhoneTiles {
            get {
                return ResourceManager.GetString("Link_iPhoneTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View SSRS mobile reports and KPIs in the iOS mobile apps.
        /// </summary>
        public static string Link_iPhoneViewSQL {
            get {
                return ResourceManager.GetString("Link_iPhoneViewSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a deep link that goes to a specific location.
        /// </summary>
        public static string Link_MobileDeepLink {
            get {
                return ResourceManager.GetString("Link_MobileDeepLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get notifications in the Power BI mobile apps.
        /// </summary>
        public static string Link_MobileNotificationCenter {
            get {
                return ResourceManager.GetString("Link_MobileNotificationCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Power BI data from the real world with the mobile apps.
        /// </summary>
        public static string Link_MobileRealWorld {
            get {
                return ResourceManager.GetString("Link_MobileRealWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using OAuth to connect to Reporting Services.
        /// </summary>
        public static string Link_OAuthSSRS {
            get {
                return ResourceManager.GetString("Link_OAuthSSRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View your data offline in the Power BI mobile apps.
        /// </summary>
        public static string Link_OfflineAndroid {
            get {
                return ResourceManager.GetString("Link_OfflineAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and interact with Power BI reports optimized for your phone.
        /// </summary>
        public static string Link_ViewPhoneReport {
            get {
                return ResourceManager.GetString("Link_ViewPhoneReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s new in the mobile apps for Power BI.
        /// </summary>
        public static string Link_WhatsNew {
            get {
                return ResourceManager.GetString("Link_WhatsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Reporting Services mobile reports and KPIs on the Power BI mobile app for Windows 10.
        /// </summary>
        public static string Link_Windows10KPIs {
            get {
                return ResourceManager.GetString("Link_Windows10KPIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started with the Power BI mobile app for Windows 10.
        /// </summary>
        public static string Link_WindowsGetStarted {
            get {
                return ResourceManager.GetString("Link_WindowsGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin a Power BI tile or dashboard to the Start screen.
        /// </summary>
        public static string Link_WindowsPin {
            get {
                return ResourceManager.GetString("Link_WindowsPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Power BI in presentation mode on Surface Hub.
        /// </summary>
        public static string Link_WindowsPresentationMode {
            get {
                return ResourceManager.GetString("Link_WindowsPresentationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports in the Power BI mobile app for Windows 10.
        /// </summary>
        public static string Link_WindowsReports {
            get {
                return ResourceManager.GetString("Link_WindowsReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share a tile from the Power BI mobile app for Windows 10.
        /// </summary>
        public static string Link_WindowsShareTile {
            get {
                return ResourceManager.GetString("Link_WindowsShareTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiles in the Power BI mobile app for Windows 10.
        /// </summary>
        public static string Link_WindowsTiles {
            get {
                return ResourceManager.GetString("Link_WindowsTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI Mobile Apps.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
