//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBI.Resources.Shared.Lefties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class service {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal service() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerBI.Resources.Shared.Lefties.service", typeof(service).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Area_Administration {
            get {
                return ResourceManager.GetString("Area_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask questions of your data.
        /// </summary>
        public static string Area_Ask {
            get {
                return ResourceManager.GetString("Area_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to services.
        /// </summary>
        public static string Area_Connect {
            get {
                return ResourceManager.GetString("Area_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboards.
        /// </summary>
        public static string Area_Dashboards {
            get {
                return ResourceManager.GetString("Area_Dashboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data from databases.
        /// </summary>
        public static string Area_DataDatabases {
            get {
                return ResourceManager.GetString("Area_DataDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data from files.
        /// </summary>
        public static string Area_DataFiles {
            get {
                return ResourceManager.GetString("Area_DataFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data refresh.
        /// </summary>
        public static string Area_DataRefresh {
            get {
                return ResourceManager.GetString("Area_DataRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateways.
        /// </summary>
        public static string Area_Gateways {
            get {
                return ResourceManager.GetString("Area_Gateways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        public static string Area_GetStarted {
            get {
                return ResourceManager.GetString("Area_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Area_Reports {
            get {
                return ResourceManager.GetString("Area_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Area_Resources {
            get {
                return ResourceManager.GetString("Area_Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        public static string Area_Samples {
            get {
                return ResourceManager.GetString("Area_Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share your work.
        /// </summary>
        public static string Area_Share {
            get {
                return ResourceManager.GetString("Area_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshooting.
        /// </summary>
        public static string Area_Troubleshooting {
            get {
                return ResourceManager.GetString("Area_Troubleshooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizations.
        /// </summary>
        public static string Area_Visualizations {
            get {
                return ResourceManager.GetString("Area_Visualizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI get started with third party apps.
        /// </summary>
        public static string Link_3rdPartyGetStarted {
            get {
                return ResourceManager.GetString("Link_3rdPartyGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acumatica content pack.
        /// </summary>
        public static string Link_Acumatica {
            get {
                return ResourceManager.GetString("Link_Acumatica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a filter to a report in Power BI.
        /// </summary>
        public static string Link_AddFilterToReport {
            get {
                return ResourceManager.GetString("Link_AddFilterToReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an image to a dashboard.
        /// </summary>
        public static string Link_AddImageToDashboard {
            get {
                return ResourceManager.GetString("Link_AddImageToDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a page to a Power BI report.
        /// </summary>
        public static string Link_AddPageToReport {
            get {
                return ResourceManager.GetString("Link_AddPageToReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial: Part I, Add visualizations to a Power BI report.
        /// </summary>
        public static string Link_AddVisualizations1 {
            get {
                return ResourceManager.GetString("Link_AddVisualizations1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial: Part 2, Add visualizations to a Power BI report.
        /// </summary>
        public static string Link_AddVisualizations2 {
            get {
                return ResourceManager.GetString("Link_AddVisualizations2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an image, text box, video, or web code to your dashboard.
        /// </summary>
        public static string Link_AddWidget {
            get {
                return ResourceManager.GetString("Link_AddWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditing Power BI.
        /// </summary>
        public static string Link_AdminAuditing {
            get {
                return ResourceManager.GetString("Link_AdminAuditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administering Power BI in your organization.
        /// </summary>
        public static string Link_Administering {
            get {
                return ResourceManager.GetString("Link_Administering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin portal.
        /// </summary>
        public static string Link_AdminPortal {
            get {
                return ResourceManager.GetString("Link_AdminPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration Role in Office 365.
        /// </summary>
        public static string Link_AdminRole {
            get {
                return ResourceManager.GetString("Link_AdminRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adobe Analytics content pack.
        /// </summary>
        public static string Link_AdobeAnalytics {
            get {
                return ResourceManager.GetString("Link_AdobeAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregates (sum, average, maximum, etc.) in Power BI.
        /// </summary>
        public static string Link_Aggregates {
            get {
                return ResourceManager.GetString("Link_Aggregates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpine Metrics Sales Predictions content pack.
        /// </summary>
        public static string Link_AlpineMetrics {
            get {
                return ResourceManager.GetString("Link_AlpineMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Email Address for Power BI.
        /// </summary>
        public static string Link_AlternateEmail {
            get {
                return ResourceManager.GetString("Link_AlternateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your enterprise data source - Analysis Services.
        /// </summary>
        public static string Link_AnalysisServices {
            get {
                return ResourceManager.GetString("Link_AnalysisServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshooting Analyze in Excel.
        /// </summary>
        public static string Link_AnalyzeExcelTroubleshoot {
            get {
                return ResourceManager.GetString("Link_AnalyzeExcelTroubleshoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze in Excel.
        /// </summary>
        public static string Link_AnalyzeInExcel {
            get {
                return ResourceManager.GetString("Link_AnalyzeInExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appFigures content pack.
        /// </summary>
        public static string Link_AppFigures {
            get {
                return ResourceManager.GetString("Link_AppFigures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Insights content pack.
        /// </summary>
        public static string Link_AppInisghts {
            get {
                return ResourceManager.GetString("Link_AppInisghts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial: ArcGIS in Power BI.
        /// </summary>
        public static string Link_ArcGIS {
            get {
                return ResourceManager.GetString("Link_ArcGIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI Archived Workspace.
        /// </summary>
        public static string Link_ArchivedWorkspace {
            get {
                return ResourceManager.GetString("Link_ArchivedWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AT Internet Bridge content pack.
        /// </summary>
        public static string Link_AtInternetBridge {
            get {
                return ResourceManager.GetString("Link_AtInternetBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure and Power BI.
        /// </summary>
        public static string Link_Azure {
            get {
                return ResourceManager.GetString("Link_Azure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Audit Logs content pack.
        /// </summary>
        public static string Link_AzureAuditLogs {
            get {
                return ResourceManager.GetString("Link_AzureAuditLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up with a custom Azure directory.
        /// </summary>
        public static string Link_AzureDirectory {
            get {
                return ResourceManager.GetString("Link_AzureDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Azure Enterprise content pack.
        /// </summary>
        public static string Link_AzureEnterprise {
            get {
                return ResourceManager.GetString("Link_AzureEnterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Search content pack.
        /// </summary>
        public static string Link_AzureSearch {
            get {
                return ResourceManager.GetString("Link_AzureSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Security Center content pack.
        /// </summary>
        public static string Link_AzureSecurity {
            get {
                return ResourceManager.GetString("Link_AzureSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial: Basic Area chart.
        /// </summary>
        public static string Link_BasicAreaChart {
            get {
                return ResourceManager.GetString("Link_BasicAreaChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI - basic concepts.
        /// </summary>
        public static string Link_BasicConcepts {
            get {
                return ResourceManager.GetString("Link_BasicConcepts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a big number tile for a Power BI dashboard by asking a question.
        /// </summary>
        public static string Link_BigNumberTileDashboard {
            get {
                return ResourceManager.GetString("Link_BigNumberTileDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a big number tile from a Power BI report.
        /// </summary>
        public static string Link_BigNumberTileReport {
            get {
                return ResourceManager.GetString("Link_BigNumberTileReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing content pack.
        /// </summary>
        public static string Link_Bing {
            get {
                return ResourceManager.GetString("Link_Bing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported browsers for Power BI.
        /// </summary>
        public static string Link_BrowserSupport {
            get {
                return ResourceManager.GetString("Link_BrowserSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturing additional diagnostic information for Power BI.
        /// </summary>
        public static string Link_CapturingDiag {
            get {
                return ResourceManager.GetString("Link_CapturingDiag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page display settings in a Power BI report.
        /// </summary>
        public static string Link_ChangeReportDisplaySettings {
            get {
                return ResourceManager.GetString("Link_ChangeReportDisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the type of visualization in a Power BI report.
        /// </summary>
        public static string Link_ChangeTypeVisualization {
            get {
                return ResourceManager.GetString("Link_ChangeTypeVisualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change how a chart is sorted in a Power BI report.
        /// </summary>
        public static string Link_ChartSorting {
            get {
                return ResourceManager.GetString("Link_ChartSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circuit ID content pack.
        /// </summary>
        public static string Link_CircuitID {
            get {
                return ResourceManager.GetString("Link_CircuitID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClickDimensions content pack.
        /// </summary>
        public static string Link_ClickDimensions {
            get {
                return ResourceManager.GetString("Link_ClickDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing your Power BI Account.
        /// </summary>
        public static string Link_ClosingAccount {
            get {
                return ResourceManager.GetString("Link_ClosingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaborate in your Power BI group workspace.
        /// </summary>
        public static string Link_CollaborateWithGroup {
            get {
                return ResourceManager.GetString("Link_CollaborateWithGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting started with color formatting and axis properties.
        /// </summary>
        public static string Link_ColorFormatting {
            get {
                return ResourceManager.GetString("Link_ColorFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips and tricks for color formatting in Power BI.
        /// </summary>
        public static string Link_ColorFormattingTips {
            get {
                return ResourceManager.GetString("Link_ColorFormattingTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial: Combo Chart in Power BI.
        /// </summary>
        public static string Link_ComboChart {
            get {
                return ResourceManager.GetString("Link_ComboChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comScore Digital Analytix content pack.
        /// </summary>
        public static string Link_ComScore {
            get {
                return ResourceManager.GetString("Link_ComScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure mobile apps with Intune.
        /// </summary>
        public static string Link_ConfigureIntune {
            get {
                return ResourceManager.GetString("Link_ConfigureIntune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring proxy settings.
        /// </summary>
        public static string Link_ConfigureProxy {
            get {
                return ResourceManager.GetString("Link_ConfigureProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to files on your group&apos;s OneDrive for Business.
        /// </summary>
        public static string Link_ConnectOneDrive {
            get {
                return ResourceManager.GetString("Link_ConnectOneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial: Using the Power BI sample content packs.
        /// </summary>
        public static string Link_ConnectToSamples {
            get {
                return ResourceManager.GetString("Link_ConnectToSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to services with content packs.
        /// </summary>
        public static string Link_ConnectToServices {
            get {
                return ResourceManager.GetString("Link_ConnectToServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy and paste a visualization in Power BI.
        /// </summary>
        public static string Link_CopyPasteVisual {
            get {
                return ResourceManager.GetString("Link_CopyPasteVisual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Power BI dashboard.
        /// </summary>
        public static string Link_CreateADashboard {
            get {
                return ResourceManager.GetString("Link_CreateADashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create featured questions for Power BI Q&amp;A.
        /// </summary>
        public static string Link_CreateFeaturedQuestions {
            get {
                return ResourceManager.GetString("Link_CreateFeaturedQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a group in Power BI.
        /// </summary>
        public static string Link_CreateGroup {
            get {
                return ResourceManager.GetString("Link_CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a phone view of a dashboard.
        /// </summary>
        public static string Link_CreatePhoneViewDashboard {
            get {
                return ResourceManager.GetString("Link_CreatePhoneViewDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and publish an organizational content pack (tutorial).
        /// </summary>
        public static string Link_CreatePublishContentPack {
            get {
                return ResourceManager.GetString("Link_CreatePublishContentPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Power BI report.
        /// </summary>
        public static string Link_CreateReport {
            get {
                return ResourceManager.GetString("Link_CreateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Profitability sample for Power BI: Take a tour.
        /// </summary>
        public static string Link_CustomerProfitabilitySample {
            get {
                return ResourceManager.GetString("Link_CustomerProfitabilitySample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial: Customize visualization title, background, and legend.
        /// </summary>
        public static string Link_CustomizeVisuals {
            get {
                return ResourceManager.GetString("Link_CustomizeVisuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom visualizations in Power BI.
        /// </summary>
        public static string Link_CustomVisualizations {
            get {
                return ResourceManager.GetString("Link_CustomVisualizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a custom visualization to a Power BI report.
        /// </summary>
        public static string Link_CustomVisualizationsToReport {
            get {
                return ResourceManager.GetString("Link_CustomVisualizationsToReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial: Customize X-axis and Y-axis properties.
        /// </summary>
        public static string Link_CustomXandY {
            get {
                return ResourceManager.GetString("Link_CustomXandY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboards in Power BI.
        /// </summary>
        public static string Link_DashboardsInPowerBI {
            get {
                return ResourceManager.GetString("Link_DashboardsInPowerBI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard tiles in Power BI.
        /// </summary>
        public static string Link_DashboardTiles {
            get {
                return ResourceManager.GetString("Link_DashboardTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard data classification.
        /// </summary>
        public static string Link_DataClassification {
            get {
                return ResourceManager.GetString("Link_DataClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data refresh in Power BI.
        /// </summary>
        public static string Link_DataRefresh {
            get {
                return ResourceManager.GetString("Link_DataRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh a dataset created from a comma separated value (.csv) file on OneDrive.
        /// </summary>
        public static string Link_DataRefreshCloudCsv {
            get {
                return ResourceManager.GetString("Link_DataRefreshCloudCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh a dataset created from an Excel workbook - cloud.
        /// </summary>
        public static string Link_DataRefreshCloudExcel {
            get {
                return ResourceManager.GetString("Link_DataRefreshCloudExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh a dataset created from a Power BI Desktop file - cloud.
        /// </summary>
        public static string Link_DataRefreshDesktopCloud {
            get {
                return ResourceManager.GetString("Link_DataRefreshDesktopCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh a dataset created from a Power BI Desktop file - local.
        /// </summary>
        public static string Link_DataRefreshDesktopLocal {
            get {
                return ResourceManager.GetString("Link_DataRefreshDesktopLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh a dataset created from an Excel workbook - local.
        /// </summary>
        public static string Link_DataRefreshLocalExcel {
            get {
                return ResourceManager.GetString("Link_DataRefreshLocalExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data sources for Power BI.
        /// </summary>
        public static string Link_DataSources {
            get {
                return ResourceManager.GetString("Link_DataSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make your data work well with Q&amp;A in Power BI.
        /// </summary>
        public static string Link_DataWorkWell {
            get {
                return ResourceManager.GetString("Link_DataWorkWell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a report from Power BI.
        /// </summary>
        public static string Link_DeleteAReport {
            get {
                return ResourceManager.GetString("Link_DeleteAReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove your connection to an organizational content pack.
        /// </summary>
        public static string Link_DeleteContentPack {
            get {
                return ResourceManager.GetString("Link_DeleteContentPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a page from a Power BI report.
        /// </summary>
        public static string Link_DeletePageFromReport {
            get {
                return ResourceManager.GetString("Link_DeletePageFromReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a visualization in Power BI.
        /// </summary>
        public static string Link_DeleteVisual {
            get {
                return ResourceManager.GetString("Link_DeleteVisual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips for designing a great Power BI dashboard.
        /// </summary>
        public static string Link_DesignTips {
            get {
                return ResourceManager.GetString("Link_DesignTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spark on HDInsight with DirectQuery.
        /// </summary>
        public static string Link_DirectConnectSpark {
            get {
                return ResourceManager.GetString("Link_DirectConnectSpark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure SQL Database with DirectQuery.
        /// </summary>
        public static string Link_DirectQuerySql {
            get {
                return ResourceManager.GetString("Link_DirectQuerySql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure SQL Data Warehouse with DirectQuery.
        /// </summary>
        public static string Link_DirectQuerySqlDW {
            get {
                return ResourceManager.GetString("Link_DirectQuerySqlDW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable privacy settings.
        /// </summary>
        public static string Link_DisablePrivacyIssues {
            get {
                return ResourceManager.GetString("Link_DisablePrivacyIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display dashboards and reports in Full Screen mode (TV mode).
        /// </summary>
        public static string Link_DisplayReportFullScreen {
            get {
                return ResourceManager.GetString("Link_DisplayReportFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display a dashboard tile in Full Screen mode (TV mode).
        /// </summary>
        public static string Link_DisplayTileFullScreen {
            get {
                return ResourceManager.GetString("Link_DisplayTileFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display a dashboard tile in Focus mode.
        /// </summary>
        public static string Link_DisplayTileInFocus {
            get {
                return ResourceManager.GetString("Link_DisplayTileInFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial: Doughnut charts in Power BI.
        /// </summary>
        public static string Link_DoughnutCharts {
            get {
                return ResourceManager.GetString("Link_DoughnutCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and use custom visuals from the Office store.
        /// </summary>
        public static string Link_DownloadCustomVisual {
            get {
                return ResourceManager.GetString("Link_DownloadCustomVisual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the Financial Sample workbook for Power BI.
        /// </summary>
        public static string Link_DownloadFinancialSample {
            get {
                return ResourceManager.GetString("Link_DownloadFinancialSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drill down in a visualization in Power BI.
        /// </summary>
        public static string Link_DrillVisual {
            get {
                return ResourceManager.GetString("Link_DrillVisual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate a report page in Power BI.
        /// </summary>
        public static string Link_DuplicateReportPage {
            get {
                return ResourceManager.GetString("Link_DuplicateReportPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Dynamics AX content pack.
        /// </summary>
        public static string Link_DynamicsAX {
            get {
                return ResourceManager.GetString("Link_DynamicsAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Dynamics CRM content pack.
        /// </summary>
        public static string Link_DynamicsCRM {
            get {
                return ResourceManager.GetString("Link_DynamicsCRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Dynamics Marketing content pack.
        /// </summary>
        public static string Link_DynamicsMarketing {
            get {
                return ResourceManager.GetString("Link_DynamicsMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Dynamics NAV content pack.
        /// </summary>
        public static string Link_DynamicsNav {
            get {
                return ResourceManager.GetString("Link_DynamicsNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a tile -- resize, move, rename, pin, delete, add hyperlink.
        /// </summary>
        public static string Link_EditATile {
            get {
                return ResourceManager.GetString("Link_EditATile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go from Reading View to Editing View in Power BI.
        /// </summary>
        public static string Link_EditingView {
            get {
                return ResourceManager.GetString("Link_EditingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report editor...Take a tour.
        /// </summary>
        public static string Link_EditorTakeTour {
            get {
                return ResourceManager.GetString("Link_EditorTakeTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed report in SharePoint Online.
        /// </summary>
        public static string Link_EmbedReportSPO {
            get {
                return ResourceManager.GetString("Link_EmbedReportSPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Cortana for Power BI.
        /// </summary>
        public static string Link_EnableCortana {
            get {
                return ResourceManager.GetString("Link_EnableCortana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: We couldn&apos;t find any data in your Excel workbook.
        /// </summary>
        public static string Link_ExcelError {
            get {
                return ResourceManager.GetString("Link_ExcelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data from a visualization.
        /// </summary>
        public static string Link_ExportFromVisualization {
            get {
                return ResourceManager.GetString("Link_ExportFromVisualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI and ExpressRoute.
        /// </summary>
        public static string Link_ExpressRoute {
            get {
                return ResourceManager.GetString("Link_ExpressRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently asked questions.
        /// </summary>
        public static string Link_Faq {
            get {
                return ResourceManager.GetString("Link_Faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite dashboards in Power BI.
        /// </summary>
        public static string Link_FavoriteDashboards {
            get {
                return ResourceManager.GetString("Link_FavoriteDashboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured dashboards in Power BI.
        /// </summary>
        public static string Link_FeaturedDashboards {
            get {
                return ResourceManager.GetString("Link_FeaturedDashboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial: Filled Maps (Choropleths) in Power BI.
        /// </summary>
        public static string Link_FilledMaps {
            get {
                return ResourceManager.GetString("Link_FilledMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About filters and highlighting in Power BI reports.
        /// </summary>
        public static string Link_FiltersAndHighlighting {
            get {
                return ResourceManager.GetString("Link_FiltersAndHighlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and connect to an organizational content pack.
        /// </summary>
        public static string Link_FindOpenContentPack {
            get {
                return ResourceManager.GetString("Link_FindOpenContentPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password for Power BI?.
        /// </summary>
        public static string Link_ForgotPassword {
            get {
                return ResourceManager.GetString("Link_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI (free) in your organization.
        /// </summary>
        public static string Link_FreePowerBI {
            get {
                return ResourceManager.GetString("Link_FreePowerBI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial: Funnel charts in Power BI.
        /// </summary>
        public static string Link_FunnelCharts {
            get {
                return ResourceManager.GetString("Link_FunnelCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Q&amp;A with Power BI Gateway - Enterprise data (Preview).
        /// </summary>
        public static string Link_GatewayEnterpriseData {
            get {
                return ResourceManager.GetString("Link_GatewayEnterpriseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-premises Data Gateway.
        /// </summary>
        public static string Link_GatewayOnPrem {
            get {
                return ResourceManager.GetString("Link_GatewayOnPrem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-Premises Data Gateway FAQ.
        /// </summary>
        public static string Link_GatewayOnPremFaq {
            get {
                return ResourceManager.GetString("Link_GatewayOnPremFaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-premises Data Gateway - in-depth.
        /// </summary>
        public static string Link_GatewayOnPremInDepth {
            get {
                return ResourceManager.GetString("Link_GatewayOnPremInDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your data source - Oracle.
        /// </summary>
        public static string Link_GatewayOnPremOracle {
            get {
                return ResourceManager.GetString("Link_GatewayOnPremOracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshooting the On-Premises Data Gateway.
        /// </summary>
        public static string Link_GatewayOnPremTshoot {
            get {
                return ResourceManager.GetString("Link_GatewayOnPremTshoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get data from Comma Separated Value (.CSV) files.
        /// </summary>
        public static string Link_GetDataCSV {
            get {
                return ResourceManager.GetString("Link_GetDataCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get data from Power BI Desktop files.
        /// </summary>
        public static string Link_GetDataDesktop {
            get {
                return ResourceManager.GetString("Link_GetDataDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish to Power BI from Excel 2016.
        /// </summary>
        public static string Link_GetDataFromExcel {
            get {
                return ResourceManager.GetString("Link_GetDataFromExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get data from files.
        /// </summary>
        public static string Link_GetDataIn {
            get {
                return ResourceManager.GetString("Link_GetDataIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started with Power BI.
        /// </summary>
        public static string Link_GetStarted {
            get {
                return ResourceManager.GetString("Link_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial: Get Started with Power BI Q&amp;A.
        /// </summary>
        public static string Link_GetStartedTutorial {
            get {
                return ResourceManager.GetString("Link_GetStartedTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub content pack.
        /// </summary>
        public static string Link_GitHub {
            get {
                return ResourceManager.GetString("Link_GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Analytics content pack.
        /// </summary>
        public static string Link_GoogleAnalytics {
            get {
                return ResourceManager.GetString("Link_GoogleAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI Governance and Deployment Approaches.
        /// </summary>
        public static string Link_Governance {
            get {
                return ResourceManager.GetString("Link_Governance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI for US Government.
        /// </summary>
        public static string Link_GovUSOverview {
            get {
                return ResourceManager.GetString("Link_GovUSOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroll your US Government organization.
        /// </summary>
        public static string Link_GovUSSignup {
            get {
                return ResourceManager.GetString("Link_GovUSSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histograms.
        /// </summary>
        public static string Link_Histograms {
            get {
                return ResourceManager.GetString("Link_Histograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips and Tricks for Power BI Map visualizations.
        /// </summary>
        public static string Link_HistogramsTips {
            get {
                return ResourceManager.GetString("Link_HistogramsTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use Power BI Q&amp;A.
        /// </summary>
        public static string Link_HowToUse {
            get {
                return ResourceManager.GetString("Link_HowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Resources sample: Take a tour.
        /// </summary>
        public static string Link_HumanResourceSample {
            get {
                return ResourceManager.GetString("Link_HumanResourceSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperlinks in tables.
        /// </summary>
        public static string Link_HyperlinksInTables {
            get {
                return ResourceManager.GetString("Link_HyperlinksInTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a hyperlink to a Text Box in a Power BI report.
        /// </summary>
        public static string Link_HyperLinkToTextbox {
            get {
                return ResourceManager.GetString("Link_HyperLinkToTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your enterprise data source - Import/Scheduled Refresh.
        /// </summary>
        public static string Link_ImportScheduledRefresh {
            get {
                return ResourceManager.GetString("Link_ImportScheduledRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insightly content pack.
        /// </summary>
        public static string Link_Insightly {
            get {
                return ResourceManager.GetString("Link_Insightly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntelliBoard content pack.
        /// </summary>
        public static string Link_IntelliBoard {
            get {
                return ResourceManager.GetString("Link_IntelliBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interact with a report in Editing View in Power BI.
        /// </summary>
        public static string Link_InteractEditingView {
            get {
                return ResourceManager.GetString("Link_InteractEditingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interact with a report in Reading View in Power BI.
        /// </summary>
        public static string Link_InteractReadingView {
            get {
                return ResourceManager.GetString("Link_InteractReadingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction to Cortana for Power BI.
        /// </summary>
        public static string Link_IntroToCortana {
            get {
                return ResourceManager.GetString("Link_IntroToCortana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPI Visuals.
        /// </summary>
        public static string Link_KPIVisuals {
            get {
                return ResourceManager.GetString("Link_KPIVisuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported languages and countries/regions for Power BI.
        /// </summary>
        public static string Link_LanguageSupport {
            get {
                return ResourceManager.GetString("Link_LanguageSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithium content pack.
        /// </summary>
        public static string Link_Lithium {
            get {
                return ResourceManager.GetString("Link_Lithium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-time streaming in Power BI (Preview).
        /// </summary>
        public static string Link_LiveStreaming {
            get {
                return ResourceManager.GetString("Link_LiveStreaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MailChimp content pack.
        /// </summary>
        public static string Link_MailChimp {
            get {
                return ResourceManager.GetString("Link_MailChimp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your data capacity in Power BI.
        /// </summary>
        public static string Link_ManageCapacity {
            get {
                return ResourceManager.GetString("Link_ManageCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage, update, and delete organizational content packs.
        /// </summary>
        public static string Link_ManageContentPack {
            get {
                return ResourceManager.GetString("Link_ManageContentPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your group in Power BI and Office 365.
        /// </summary>
        public static string Link_ManageGroup {
            get {
                return ResourceManager.GetString("Link_ManageGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandrill content pack.
        /// </summary>
        public static string Link_Mandrill {
            get {
                return ResourceManager.GetString("Link_Mandrill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketo content pack.
        /// </summary>
        public static string Link_Marketo {
            get {
                return ResourceManager.GetString("Link_Marketo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Mobile Engagement content pack.
        /// </summary>
        public static string Link_MobileEngagement {
            get {
                return ResourceManager.GetString("Link_MobileEngagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move, resize, and pop out a visualization in a Power BI report.
        /// </summary>
        public static string Link_MoveVisual {
            get {
                return ResourceManager.GetString("Link_MoveVisual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new Power BI navigation experience.
        /// </summary>
        public static string Link_NewNav {
            get {
                return ResourceManager.GetString("Link_NewNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI for Office 365 is transitioned to Power BI.
        /// </summary>
        public static string Link_O365PortalRetired {
            get {
                return ResourceManager.GetString("Link_O365PortalRetired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office365Mon content pack.
        /// </summary>
        public static string Link_Office365 {
            get {
                return ResourceManager.GetString("Link_Office365", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 365 dedicated - known issues.
        /// </summary>
        public static string Link_OfficeDedicatedIssues {
            get {
                return ResourceManager.GetString("Link_OfficeDedicatedIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity Analysis sample for Power BI: Take a tour.
        /// </summary>
        public static string Link_OpportunityAnalysisSample {
            get {
                return ResourceManager.GetString("Link_OpportunityAnalysisSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize your data for Power BI Quick Insights.
        /// </summary>
        public static string Link_OptimizeData {
            get {
                return ResourceManager.GetString("Link_OptimizeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizational content packs: Introduction.
        /// </summary>
        public static string Link_OrganizationalContentPacksIntro {
            get {
                return ResourceManager.GetString("Link_OrganizationalContentPacksIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI Gateway - Personal.
        /// </summary>
        public static string Link_PersonalGateway {
            get {
                return ResourceManager.GetString("Link_PersonalGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshooting Power BI Gateway - Personal.
        /// </summary>
        public static string Link_PersonalGatewayTroubleshoot {
            get {
                return ResourceManager.GetString("Link_PersonalGatewayTroubleshoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin a tile from one dashboard to another dashboard.
        /// </summary>
        public static string Link_PinATileFromDashboard {
            get {
                return ResourceManager.GetString("Link_PinATileFromDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin a tile to a Power BI dashboard from Excel.
        /// </summary>
        public static string Link_PinATileFromExcel {
            get {
                return ResourceManager.GetString("Link_PinATileFromExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin a tile to a Power BI dashboard from a report.
        /// </summary>
        public static string Link_PinATileFromReport {
            get {
                return ResourceManager.GetString("Link_PinATileFromReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin a tile to a Power BI dashboard from the Q&amp;A question box.
        /// </summary>
        public static string Link_PinATileToDashboardFromQA {
            get {
                return ResourceManager.GetString("Link_PinATileToDashboardFromQA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin an entire report page to a Power BI dashboard.
        /// </summary>
        public static string Link_PinReportToDashboard {
            get {
                return ResourceManager.GetString("Link_PinReportToDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planview Enterprise content pack.
        /// </summary>
        public static string Link_Planview {
            get {
                return ResourceManager.GetString("Link_Planview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish to PowerPoint.
        /// </summary>
        public static string Link_PowerPoint {
            get {
                return ResourceManager.GetString("Link_PowerPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevedere content pack.
        /// </summary>
        public static string Link_Prevedere {
            get {
                return ResourceManager.GetString("Link_Prevedere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opt-in for Power BI preview features.
        /// </summary>
        public static string Link_PreviewFeatures {
            get {
                return ResourceManager.GetString("Link_PreviewFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print a dashboard, print a dashboard tile, print a report page.
        /// </summary>
        public static string Link_Printing {
            get {
                return ResourceManager.GetString("Link_Printing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurement Analysis sample: Take a tour.
        /// </summary>
        public static string Link_ProcurementAnalysisSample {
            get {
                return ResourceManager.GetString("Link_ProcurementAnalysisSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Madeira content pack.
        /// </summary>
        public static string Link_ProjectMadeira {
            get {
                return ResourceManager.GetString("Link_ProjectMadeira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Online content pack.
        /// </summary>
        public static string Link_ProjectOnline {
            get {
                return ResourceManager.GetString("Link_ProjectOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projectplace content pack.
        /// </summary>
        public static string Link_ProjectPlace {
            get {
                return ResourceManager.GetString("Link_ProjectPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI Pro content - what is it?.
        /// </summary>
        public static string Link_ProWhatIs {
            get {
                return ResourceManager.GetString("Link_ProWhatIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI publisher for Excel.
        /// </summary>
        public static string Link_PublishForExcel {
            get {
                return ResourceManager.GetString("Link_PublishForExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial: From Excel workbook to stunning report in no time.
        /// </summary>
        public static string Link_PublishFromExcel {
            get {
                return ResourceManager.GetString("Link_PublishFromExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish from Power BI to the web.
        /// </summary>
        public static string Link_PublishToWeb {
            get {
                return ResourceManager.GetString("Link_PublishToWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchasing Power BI Pro.
        /// </summary>
        public static string Link_PurchasingPro {
            get {
                return ResourceManager.GetString("Link_PurchasingPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q&amp;A in Power BI.
        /// </summary>
        public static string Link_QandA {
            get {
                return ResourceManager.GetString("Link_QandA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a QR code for a report.
        /// </summary>
        public static string Link_QRCodeForReport {
            get {
                return ResourceManager.GetString("Link_QRCodeForReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a QR code for a tile.
        /// </summary>
        public static string Link_QrCodeTile {
            get {
                return ResourceManager.GetString("Link_QrCodeTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Quality Analysis sample for Power BI: Take a tour.
        /// </summary>
        public static string Link_QualityAnalysisSample {
            get {
                return ResourceManager.GetString("Link_QualityAnalysisSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickBooks Online content pack.
        /// </summary>
        public static string Link_Quickbooks {
            get {
                return ResourceManager.GetString("Link_Quickbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Insights in Power BI.
        /// </summary>
        public static string Link_QuickInisghts {
            get {
                return ResourceManager.GetString("Link_QuickInisghts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types of Quick Insights supported by Power BI.
        /// </summary>
        public static string Link_QuickInisghtsTypes {
            get {
                return ResourceManager.GetString("Link_QuickInisghtsTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial: Radial Gauge charts in Power BI.
        /// </summary>
        public static string Link_RadialGauge {
            get {
                return ResourceManager.GetString("Link_RadialGauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Power BI report in Reading View.
        /// </summary>
        public static string Link_ReadingView {
            get {
                return ResourceManager.GetString("Link_ReadingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce the size of an Excel workbook to view it in Power BI.
        /// </summary>
        public static string Link_ReduceExcel {
            get {
                return ResourceManager.GetString("Link_ReduceExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a dashboard.
        /// </summary>
        public static string Link_RemoveDashboard {
            get {
                return ResourceManager.GetString("Link_RemoveDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename a Power BI dashboard.
        /// </summary>
        public static string Link_RenameDashboard {
            get {
                return ResourceManager.GetString("Link_RenameDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename a report in Power BI.
        /// </summary>
        public static string Link_RenameReport {
            get {
                return ResourceManager.GetString("Link_RenameReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename a report page in Power BI.
        /// </summary>
        public static string Link_RenameReportPage {
            get {
                return ResourceManager.GetString("Link_RenameReportPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder pages in a report in Power BI.
        /// </summary>
        public static string Link_ReorderPages {
            get {
                return ResourceManager.GetString("Link_ReorderPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports in Power BI.
        /// </summary>
        public static string Link_Reports {
            get {
                return ResourceManager.GetString("Link_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See the data used to create the visual.
        /// </summary>
        public static string Link_ReportsSeeData {
            get {
                return ResourceManager.GetString("Link_ReportsSeeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips and tricks for creating reports in Power BI service.
        /// </summary>
        public static string Link_ReportTipsTricks {
            get {
                return ResourceManager.GetString("Link_ReportTipsTricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Analysis sample for Power BI: Take a tour.
        /// </summary>
        public static string Link_RetailAnalysisSample {
            get {
                return ResourceManager.GetString("Link_RetailAnalysisSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row-level security with Power BI.
        /// </summary>
        public static string Link_RowLevel {
            get {
                return ResourceManager.GetString("Link_RowLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create advanced analytics and visualizations using R scripts in Power BI.
        /// </summary>
        public static string Link_RVisuals {
            get {
                return ResourceManager.GetString("Link_RVisuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesforce content pack.
        /// </summary>
        public static string Link_Salesforce {
            get {
                return ResourceManager.GetString("Link_Salesforce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales &amp; Marketing sample for Power BI: Take a tour.
        /// </summary>
        public static string Link_SalesMarketingSample {
            get {
                return ResourceManager.GetString("Link_SalesMarketingSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use the same account login for Power BI and Azure.
        /// </summary>
        public static string Link_SameAzureAccount {
            get {
                return ResourceManager.GetString("Link_SameAzureAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples for Power BI.
        /// </summary>
        public static string Link_SampleDatasets {
            get {
                return ResourceManager.GetString("Link_SampleDatasets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your enterprise data source - SAP HANA.
        /// </summary>
        public static string Link_SapHana {
            get {
                return ResourceManager.GetString("Link_SapHana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save a report in Power BI.
        /// </summary>
        public static string Link_SaveAReport {
            get {
                return ResourceManager.GetString("Link_SaveAReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial: Scatter Charts in Power BI.
        /// </summary>
        public static string Link_ScatterCharts {
            get {
                return ResourceManager.GetString("Link_ScatterCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure scheduled refresh.
        /// </summary>
        public static string Link_ScheduledRefresh {
            get {
                return ResourceManager.GetString("Link_ScheduledRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshooting scheduled refresh for Azure SQL Databases.
        /// </summary>
        public static string Link_ScheduledSqlRefresh {
            get {
                return ResourceManager.GetString("Link_ScheduledSqlRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI Security.
        /// </summary>
        public static string Link_Security {
            get {
                return ResourceManager.GetString("Link_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-Service Signup for Power BI.
        /// </summary>
        public static string Link_SelfServiceSignup {
            get {
                return ResourceManager.GetString("Link_SelfServiceSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendGrid content pack.
        /// </summary>
        public static string Link_Sendgrid {
            get {
                return ResourceManager.GetString("Link_Sendgrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI Unified Notification Center.
        /// </summary>
        public static string Link_ServiceNotificationCenter {
            get {
                return ResourceManager.GetString("Link_ServiceNotificationCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceNow Incidents content pack.
        /// </summary>
        public static string Link_ServiceNow {
            get {
                return ResourceManager.GetString("Link_ServiceNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data alerts in Power BI service.
        /// </summary>
        public static string Link_ServiceSetAlerts {
            get {
                return ResourceManager.GetString("Link_ServiceSetAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How should I collaborate on &amp; share dashboards and reports?.
        /// </summary>
        public static string Link_ShareDashboard {
            get {
                return ResourceManager.GetString("Link_ShareDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share a dashboard that links to an Excel workbook on OneDrive for Business.
        /// </summary>
        public static string Link_ShareDashboardLinkExcel {
            get {
                return ResourceManager.GetString("Link_ShareDashboardLinkExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share a dashboard with colleagues and others.
        /// </summary>
        public static string Link_ShareUnshareDashboard {
            get {
                return ResourceManager.GetString("Link_ShareUnshareDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing up for Power BI with a new Office 365 Trial.
        /// </summary>
        public static string Link_SigningUpWithOffice {
            get {
                return ResourceManager.GetString("Link_SigningUpWithOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial: Slicers in Power BI.
        /// </summary>
        public static string Link_Slicers {
            get {
                return ResourceManager.GetString("Link_Slicers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smartsheet content pack.
        /// </summary>
        public static string Link_Smartsheet {
            get {
                return ResourceManager.GetString("Link_Smartsheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SparkPost content pack.
        /// </summary>
        public static string Link_Sparkpost {
            get {
                return ResourceManager.GetString("Link_Sparkpost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT Spend Analysis sample for Power BI: Take a tour.
        /// </summary>
        public static string Link_SpendAnalysisSample {
            get {
                return ResourceManager.GetString("Link_SpendAnalysisSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your enterprise data source - SQL.
        /// </summary>
        public static string Link_Sql {
            get {
                return ResourceManager.GetString("Link_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Database Auditing content pack.
        /// </summary>
        public static string Link_SqlAuditing {
            get {
                return ResourceManager.GetString("Link_SqlAuditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Sentry content pack.
        /// </summary>
        public static string Link_SqlSentry {
            get {
                return ResourceManager.GetString("Link_SqlSentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server Analysis Services live data in Power BI.
        /// </summary>
        public static string Link_SSASTabular {
            get {
                return ResourceManager.GetString("Link_SSASTabular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stripe content pack.
        /// </summary>
        public static string Link_Stripe {
            get {
                return ResourceManager.GetString("Link_Stripe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SweetIQ content pack.
        /// </summary>
        public static string Link_SweetIQ {
            get {
                return ResourceManager.GetString("Link_SweetIQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Boxes in Power BI reports.
        /// </summary>
        public static string Link_TextboxesReports {
            get {
                return ResourceManager.GetString("Link_TextboxesReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshooting tile errors.
        /// </summary>
        public static string Link_TileErrors {
            get {
                return ResourceManager.GetString("Link_TileErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips and tricks for asking questions with Q&amp;A in Power BI.
        /// </summary>
        public static string Link_TipsForAsking {
            get {
                return ResourceManager.GetString("Link_TipsForAsking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 tips for getting help.
        /// </summary>
        public static string Link_TipsGettingHelp {
            get {
                return ResourceManager.GetString("Link_TipsGettingHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial: Treemaps in Power BI.
        /// </summary>
        public static string Link_Treemaps {
            get {
                return ResourceManager.GetString("Link_Treemaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshooting refresh scenarios.
        /// </summary>
        public static string Link_TroubleshootingRefreshScenarios {
            get {
                return ResourceManager.GetString("Link_TroubleshootingRefreshScenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troux content pack.
        /// </summary>
        public static string Link_Troux {
            get {
                return ResourceManager.GetString("Link_Troux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial: Change the display settings for a page in a Power BI report.
        /// </summary>
        public static string Link_TutorialChangeReport {
            get {
                return ResourceManager.GetString("Link_TutorialChangeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twilio content pack.
        /// </summary>
        public static string Link_Twilio {
            get {
                return ResourceManager.GetString("Link_Twilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tyGraph content pack.
        /// </summary>
        public static string Link_Tygraph {
            get {
                return ResourceManager.GetString("Link_Tygraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add Power BI to O365 partner.
        /// </summary>
        public static string Link_UnableToAddOfficePartner {
            get {
                return ResourceManager.GetString("Link_UnableToAddOfficePartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshooting unsupported data source for refresh.
        /// </summary>
        public static string Link_UnsupportedData {
            get {
                return ResourceManager.GetString("Link_UnsupportedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use report filters.
        /// </summary>
        public static string Link_UseAReportFilter {
            get {
                return ResourceManager.GetString("Link_UseAReportFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserVoice content pack.
        /// </summary>
        public static string Link_Uservoice {
            get {
                return ResourceManager.GetString("Link_Uservoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI Videos.
        /// </summary>
        public static string Link_Videos {
            get {
                return ResourceManager.GetString("Link_Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change how visuals interact in a report.
        /// </summary>
        public static string Link_VisualInteraction {
            get {
                return ResourceManager.GetString("Link_VisualInteraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizations in Power BI.
        /// </summary>
        public static string Link_Visualizations {
            get {
                return ResourceManager.GetString("Link_Visualizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualization types in Power BI.
        /// </summary>
        public static string Link_VisualizationTypes {
            get {
                return ResourceManager.GetString("Link_VisualizationTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio Team Services content pack.
        /// </summary>
        public static string Link_VisualStudioOnline {
            get {
                return ResourceManager.GetString("Link_VisualStudioOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VMob content pack.
        /// </summary>
        public static string Link_VMob {
            get {
                return ResourceManager.GetString("Link_VMob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial: Waterfall charts in Power BI.
        /// </summary>
        public static string Link_Waterfall {
            get {
                return ResourceManager.GetString("Link_Waterfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI webinars.
        /// </summary>
        public static string Link_Webinars {
            get {
                return ResourceManager.GetString("Link_Webinars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webtrends content pack.
        /// </summary>
        public static string Link_Webtrends {
            get {
                return ResourceManager.GetString("Link_Webtrends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s new in the Power BI service.
        /// </summary>
        public static string Link_WhatsNew {
            get {
                return ResourceManager.GetString("Link_WhatsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where is my tenant located?.
        /// </summary>
        public static string Link_WhereIsMyTenant {
            get {
                return ResourceManager.GetString("Link_WhereIsMyTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whitepapers.
        /// </summary>
        public static string Link_Whitepapers {
            get {
                return ResourceManager.GetString("Link_Whitepapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get data from Excel workbook files.
        /// </summary>
        public static string Link_WholeExcel {
            get {
                return ResourceManager.GetString("Link_WholeExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Dev Center content pack.
        /// </summary>
        public static string Link_WindowsDevCenter {
            get {
                return ResourceManager.GetString("Link_WindowsDevCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizational content packs: Copy, refresh, &amp; get access.
        /// </summary>
        public static string Link_WorkWithContentPack {
            get {
                return ResourceManager.GetString("Link_WorkWithContentPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xero content pack.
        /// </summary>
        public static string Link_Xero {
            get {
                return ResourceManager.GetString("Link_Xero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to refresh your Xero content pack credentials if refresh failed.
        /// </summary>
        public static string Link_XeroCredentialsRefresh {
            get {
                return ResourceManager.GetString("Link_XeroCredentialsRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zendesk content pack.
        /// </summary>
        public static string Link_Zendesk {
            get {
                return ResourceManager.GetString("Link_Zendesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziosk content pack.
        /// </summary>
        public static string Link_Ziosk {
            get {
                return ResourceManager.GetString("Link_Ziosk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuora content pack.
        /// </summary>
        public static string Link_Zuora {
            get {
                return ResourceManager.GetString("Link_Zuora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI Service.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
