//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBI.Resources.Pages.Developers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerBI.Resources.Pages.Developers.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide seamless, in-app analytics experiences without building
        ///them from the ground up..
        /// </summary>
        public static string API_Content {
            get {
                return ResourceManager.GetString("API_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started now.
        /// </summary>
        public static string API_CTA_GetStartedNow {
            get {
                return ResourceManager.GetString("API_CTA_GetStartedNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcing Microsoft Power BI Embedded.
        /// </summary>
        public static string API_Heading {
            get {
                return ResourceManager.GetString("API_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string ClientApp_CTA_Documentation {
            get {
                return ResourceManager.GetString("ClientApp_CTA_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register your app.
        /// </summary>
        public static string ClientApp_CTA_RegisterYourApp {
            get {
                return ResourceManager.GetString("ClientApp_CTA_RegisterYourApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string ClientApp_CTA_Sample {
            get {
                return ResourceManager.GetString("ClientApp_CTA_Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client app.
        /// </summary>
        public static string ClientApp_Heading {
            get {
                return ResourceManager.GetString("ClientApp_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our powerful REST APIs enable your users to
        ///easily pull tiles, dashboards, and reports directly
        ///into your app, make changes, and then push data
        ///back into Power BI, all without ever leaving your
        ///application..
        /// </summary>
        public static string Connect_Content {
            get {
                return ResourceManager.GetString("Connect_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string Connect_CTA_LearnMore {
            get {
                return ResourceManager.GetString("Connect_CTA_LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Power BI through your
        ///app.
        /// </summary>
        public static string Connect_Heading {
            get {
                return ResourceManager.GetString("Connect_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give your users instant insights with Power BI content packs. Create customized solutions that enable millions of users to analyze your app’s data in seconds from within Power BI..
        /// </summary>
        public static string ConnectAndAnalyze_Content {
            get {
                return ResourceManager.GetString("ConnectAndAnalyze_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect and analyze your app’s data with Power BI.
        /// </summary>
        public static string ConnectAndAnalyze_Heading {
            get {
                return ResourceManager.GetString("ConnectAndAnalyze_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a content pack to give instant insights to your users. Your content pack will includes a custom data model, dashboard, and report that help your users monitor, explore and share insights. Power BI enables your users to customize their own dashboards and reports starting with the ones you provide, so they get answers faster..
        /// </summary>
        public static string Connectors_Content1 {
            get {
                return ResourceManager.GetString("Connectors_Content1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to build your own content pack?.
        /// </summary>
        public static string Connectors_Content2 {
            get {
                return ResourceManager.GetString("Connectors_Content2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string Connectors_CTA_ContactUs {
            get {
                return ResourceManager.GetString("Connectors_CTA_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address.
        /// </summary>
        public static string Connectors_EnterEmail {
            get {
                return ResourceManager.GetString("Connectors_EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI Content Packs.
        /// </summary>
        public static string Connectors_Heading {
            get {
                return ResourceManager.GetString("Connectors_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve received your email..
        /// </summary>
        public static string Connectors_MobileFormDownloadLinkSent {
            get {
                return ResourceManager.GetString("Connectors_MobileFormDownloadLinkSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!:.
        /// </summary>
        public static string Connectors_MobileFormSuccess {
            get {
                return ResourceManager.GetString("Connectors_MobileFormSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft respects your privacy. To learn more please read our online.
        /// </summary>
        public static string Connectors_PrivacyDisclaimer {
            get {
                return ResourceManager.GetString("Connectors_PrivacyDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string Connectors_PrivacyStatement {
            get {
                return ResourceManager.GetString("Connectors_PrivacyStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all blog posts.
        /// </summary>
        public static string DevelopersBlog_CTA_ViewBlog {
            get {
                return ResourceManager.GetString("DevelopersBlog_CTA_ViewBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Power BI Blog posts.
        /// </summary>
        public static string DevelopersBlog_Heading {
            get {
                return ResourceManager.GetString("DevelopersBlog_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more videos.
        /// </summary>
        public static string DevelopersPlaylist_CTA {
            get {
                return ResourceManager.GetString("DevelopersPlaylist_CTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI developer playlist.
        /// </summary>
        public static string DevelopersPlaylist_Heading {
            get {
                return ResourceManager.GetString("DevelopersPlaylist_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Documentation_CTA_Documentation {
            get {
                return ResourceManager.GetString("Documentation_CTA_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting started.
        /// </summary>
        public static string Documentation_CTA_GettingStarted {
            get {
                return ResourceManager.GetString("Documentation_CTA_GettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI API terms.
        /// </summary>
        public static string Documentation_CTA_PowerBiApiTerms {
            get {
                return ResourceManager.GetString("Documentation_CTA_PowerBiApiTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register an app.
        /// </summary>
        public static string Documentation_CTA_RegisterAnApp {
            get {
                return ResourceManager.GetString("Documentation_CTA_RegisterAnApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting with OAUTH.
        /// </summary>
        public static string Documentation_CTA_StartingWithOauth {
            get {
                return ResourceManager.GetString("Documentation_CTA_StartingWithOauth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Documentation_Heading {
            get {
                return ResourceManager.GetString("Documentation_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed stunning, fully interactive reports into
        ///your customer-facing apps without the time and
        ///expense of building your own controls from the
        ///ground up. Choose from Power BI’s out-of-the box
        ///visuals, or build custom ones to meet your
        ///application’s unique needs..
        /// </summary>
        public static string Embed_Content {
            get {
                return ResourceManager.GetString("Embed_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started now.
        /// </summary>
        public static string Embed_CTA_GetStarted {
            get {
                return ResourceManager.GetString("Embed_CTA_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed interactive reports directly
        ///into your app.
        /// </summary>
        public static string Embed_Heading {
            get {
                return ResourceManager.GetString("Embed_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string Extend_CTA_LearnMore {
            get {
                return ResourceManager.GetString("Extend_CTA_LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Visuals.
        /// </summary>
        public static string ExtendPowerBi_CTA_CustomVisuals {
            get {
                return ResourceManager.GetString("ExtendPowerBi_CTA_CustomVisuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string ExtendPowerBi_CTA_Documentation {
            get {
                return ResourceManager.GetString("ExtendPowerBi_CTA_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See it on GitHub.
        /// </summary>
        public static string ExtendPowerBi_CTA_SeeOnGithub {
            get {
                return ResourceManager.GetString("ExtendPowerBi_CTA_SeeOnGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend Power BI.
        /// </summary>
        public static string ExtendPowerBi_Heading {
            get {
                return ResourceManager.GetString("ExtendPowerBi_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI Developer Center.
        /// </summary>
        public static string Hero_Heading {
            get {
                return ResourceManager.GetString("Hero_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        public static string Integrate_EnterYourEmail {
            get {
                return ResourceManager.GetString("Integrate_EnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft respects your privacy. To learn more please read our online.
        /// </summary>
        public static string Integrate_PrivacyDisclaimer {
            get {
                return ResourceManager.GetString("Integrate_PrivacyDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string Integrate_PrivacyStatement {
            get {
                return ResourceManager.GetString("Integrate_PrivacyStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Reference.
        /// </summary>
        public static string LearnMore_CTA_ApiReference {
            get {
                return ResourceManager.GetString("LearnMore_CTA_ApiReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string LearnMore_CTA_Community {
            get {
                return ResourceManager.GetString("LearnMore_CTA_Community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Blog.
        /// </summary>
        public static string LearnMore_CTA_DevBlog {
            get {
                return ResourceManager.GetString("LearnMore_CTA_DevBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string LearnMore_CTA_Feedback {
            get {
                return ResourceManager.GetString("LearnMore_CTA_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        public static string LearnMore_CTA_Samples {
            get {
                return ResourceManager.GetString("LearnMore_CTA_Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string LearnMore_Heading {
            get {
                return ResourceManager.GetString("LearnMore_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string META_DESCRIPTION {
            get {
                return ResourceManager.GetString("META_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string META_KEYWORDS {
            get {
                return ResourceManager.GetString("META_KEYWORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developers Center | Microsoft Power BI.
        /// </summary>
        public static string META_PAGETITLE {
            get {
                return ResourceManager.GetString("META_PAGETITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Stream Analytics.
        /// </summary>
        public static string RestApiRealTime_CTA_AzureStreamAnalytics {
            get {
                return ResourceManager.GetString("RestApiRealTime_CTA_AzureStreamAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string RestApiRealTime_CTA_Documentation {
            get {
                return ResourceManager.GetString("RestApiRealTime_CTA_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try the API.
        /// </summary>
        public static string RestApiRealTime_CTA_TryTheApi {
            get {
                return ResourceManager.GetString("RestApiRealTime_CTA_TryTheApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REST API and real time.
        /// </summary>
        public static string RestApiRealTime_Heading {
            get {
                return ResourceManager.GetString("RestApiRealTime_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create customized visual experiences that meet your users’ needs and match your app’s design. Get started quickly with Microsoft’s open-sourced, production-quality visualization code in GitHub..
        /// </summary>
        public static string Visualize_Content {
            get {
                return ResourceManager.GetString("Visualize_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualize your data how you want.
        /// </summary>
        public static string Visualize_Heading {
            get {
                return ResourceManager.GetString("Visualize_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Web_CTA_Documentation {
            get {
                return ResourceManager.GetString("Web_CTA_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register your app.
        /// </summary>
        public static string Web_CTA_RegisterYourApp {
            get {
                return ResourceManager.GetString("Web_CTA_RegisterYourApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string Web_CTA_Sample {
            get {
                return ResourceManager.GetString("Web_CTA_Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string Web_Heading {
            get {
                return ResourceManager.GetString("Web_Heading", resourceCulture);
            }
        }
    }
}
