//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBI.Resources.Pages.ExcelDashboardPublisher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerBI.Resources.Pages.ExcelDashboardPublisher.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for Office 32-bit.
        /// </summary>
        public static string D32Bit {
            get {
                return ResourceManager.GetString("D32Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for Office 64-bit.
        /// </summary>
        public static string D64Bit {
            get {
                return ResourceManager.GetString("D64Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save snapshots of important PivotTables, Charts, cell ranges, and more from across all of your spreadsheets to a single location with the Power BI publisher for Excel. Just download and install the add-in, and you’ll be pinning data from your workbook to your own Excel dashboard in seconds. Your new dashboard is easy to update and share, and comes with all of the features of the free Power BI service, such as combining multiple sheets on a single dashboard and connecting to live data from other web apps you [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Hero_Copy {
            get {
                return ResourceManager.GetString("Hero_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The easiest way to create and share Excel dashboards.
        /// </summary>
        public static string Hero_Heading {
            get {
                return ResourceManager.GetString("Hero_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI tranforms your company&apos;s data into rich visuals for you to collect and organize so you can focus on what matters to you. Stay in the know, spot trends as they happen, and push your business further..
        /// </summary>
        public static string META_DESCRIPTION {
            get {
                return ResourceManager.GetString("META_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string META_KEYWORDS {
            get {
                return ResourceManager.GetString("META_KEYWORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI publisher for Excel | Microsoft Power BI.
        /// </summary>
        public static string META_PAGETITLE {
            get {
                return ResourceManager.GetString("META_PAGETITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download in your preferred language.
        /// </summary>
        public static string PreferredLanguage {
            get {
                return ResourceManager.GetString("PreferredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Power BI, you can empower your colleagues in sales, finance, marketing, and customer support with the data stories they need to do a great job without distributing spreadsheets or signing in to different services..
        /// </summary>
        public static string RightData_Copy {
            get {
                return ResourceManager.GetString("RightData_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the right data to the right people.
        /// </summary>
        public static string RightData_Heading {
            get {
                return ResourceManager.GetString("RightData_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the Power BI publisher for Excel to turn your complex data analysis into accessible dashboards that are easy to share and even easier to understand. Update your pinned tables and ranges from inside Excel with the Pin Manager..
        /// </summary>
        public static string SaveShare_Copy {
            get {
                return ResourceManager.GetString("SaveShare_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and share Excel data outside of the grid.
        /// </summary>
        public static string SaveShare_Heading {
            get {
                return ResourceManager.GetString("SaveShare_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power BI brings together more than just Excel snapshots: you can import data from over 45 different services to just one dashboard. Combine Salesforce, Github, Stripe, and more for the ultimate metrics overview..
        /// </summary>
        public static string SingleDashboard_Copy {
            get {
                return ResourceManager.GetString("SingleDashboard_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unite multiple web services on a single dashboard.
        /// </summary>
        public static string SingleDashboard_Heading {
            get {
                return ResourceManager.GetString("SingleDashboard_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel data, web applications, and on-premises sources: Power BI brings together all your data so you can start analyzing it in seconds..
        /// </summary>
        public static string Sources_Copy {
            get {
                return ResourceManager.GetString("Sources_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try the Power BI publisher for Excel today and start sharing your key insights..
        /// </summary>
        public static string Try_Heading {
            get {
                return ResourceManager.GetString("Try_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What version of Office am I using?.
        /// </summary>
        public static string WhatVersion {
            get {
                return ResourceManager.GetString("WhatVersion", resourceCulture);
            }
        }
    }
}
