//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerBI.Resources.Pages.Partners {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerBI.Resources.Pages.Partners.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certified partners are an important part of the team! Find new business opportunities, make connections, and share your company’s talents and experience with Power BI users around the world..
        /// </summary>
        public static string BecomePartner_Copy {
            get {
                return ResourceManager.GetString("BecomePartner_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn how to &lt;a href=&quot;{0}&quot;&gt;become a Power BI partner&lt;/a&gt;..
        /// </summary>
        public static string BecomePartner_Copy2 {
            get {
                return ResourceManager.GetString("BecomePartner_Copy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string BecomePartner_Cta {
            get {
                return ResourceManager.GetString("BecomePartner_Cta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to become a Power BI Partner?.
        /// </summary>
        public static string BecomePartner_Heading {
            get {
                return ResourceManager.GetString("BecomePartner_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more solutions from our featured partners in the &lt;a href=&quot;{0}&quot;&gt;Partner Showcase&lt;/a&gt;.
        /// </summary>
        public static string FeaturedPartners_Copy {
            get {
                return ResourceManager.GetString("FeaturedPartners_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured partners.
        /// </summary>
        public static string FeaturedPartners_Heading {
            get {
                return ResourceManager.GetString("FeaturedPartners_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a partner.
        /// </summary>
        public static string FindPartner_Heading {
            get {
                return ResourceManager.GetString("FindPartner_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing all {0} partners.
        /// </summary>
        public static string FindPartner_Subheading {
            get {
                return ResourceManager.GetString("FindPartner_Subheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to get your Power BI solution implemented? Contact one of our certified partners..
        /// </summary>
        public static string Hero_Copy {
            get {
                return ResourceManager.GetString("Hero_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact a Power BI Partner.
        /// </summary>
        public static string Hero_Heading {
            get {
                return ResourceManager.GetString("Hero_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string META_DESCRIPTION {
            get {
                return ResourceManager.GetString("META_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string META_KEYWORDS {
            get {
                return ResourceManager.GetString("META_KEYWORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners | Microsoft Power BI.
        /// </summary>
        public static string META_PAGETITLE {
            get {
                return ResourceManager.GetString("META_PAGETITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a different region to available partners.
        /// </summary>
        public static string PartnersNotFound_Copy {
            get {
                return ResourceManager.GetString("PartnersNotFound_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, no partners were found in this region.
        /// </summary>
        public static string PartnersNotFound_Heading {
            get {
                return ResourceManager.GetString("PartnersNotFound_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Countries.
        /// </summary>
        public static string Selector_Countries {
            get {
                return ResourceManager.GetString("Selector_Countries", resourceCulture);
            }
        }
    }
}
